cp /mnt/c/src/smart_packages/packages/smart_lorentz_gauss/example/* smart_lorentz_gauss/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_base/example/* smart_arrays_base/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_compress/example/* smart_arrays_compress/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_contour_finder/example/* smart_arrays_contour_finder/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_dbstore/example/* smart_arrays_dbstore/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_lmfit/example/* smart_arrays_lmfit/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_numerics/example/* smart_arrays_numerics/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_peaks/example/* smart_arrays_peaks/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_plot_polyline/example/* smart_arrays_plot_polyline/ -r
cp /mnt/c/src/smart_packages/packages/smart_arrays_sample_data/example/* smart_arrays_sample_data/ -r
cp /mnt/c/src/smart_packages/packages/smart_dialogs/example/* smart_dialogs/ -r
cp /mnt/c/src/smart_packages/packages/smart_lorentz_gauss/example/* smart_lorentz_gauss/ -r
cp /mnt/c/src/smart_packages/packages/smart_signal_processing/example/* smart_signal_processing/ -r
