
var CanvasKitInit = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(CanvasKitInit) {
  CanvasKitInit = CanvasKitInit || {};


null;var r;r||(r=typeof CanvasKitInit !== 'undefined' ? CanvasKitInit : {});var aa=Object.assign,ba,ea;r.ready=new Promise(function(a,b){ba=a;ea=b});
(function(a){a.Sd=a.Sd||[];a.Sd.push(function(){a.MakeSWCanvasSurface=function(b){var c=b;if("CANVAS"!==c.tagName&&(c=document.getElementById(b),!c))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.qe=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var e={width:b,height:c,colorType:a.ColorType.RGBA_8888,alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,k=a._malloc(f);if(e=a.Surface._makeRasterDirect(e,
k,4*b))e.qe=null,e.We=b,e.Te=c,e.Ue=f,e.Ae=k,e.getCanvas().clear(a.TRANSPARENT);return e};a.MakeRasterDirectSurface=function(b,c,e){return a.Surface._makeRasterDirect(b,c.byteOffset,e)};a.Surface.prototype.flush=function(b){a.Pd(this.Od);this._flush();if(this.qe){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.Ae,this.Ue);c=new ImageData(c,this.We,this.Te);b?this.qe.getContext("2d").putImageData(c,0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.qe.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=
function(){this.Ae&&a._free(this.Ae);this.delete()};a.Pd=a.Pd||function(){};a.re=a.re||function(){return null}})})(r);
(function(a){a.Sd=a.Sd||[];a.Sd.push(function(){function b(m,q,x){return m&&m.hasOwnProperty(q)?m[q]:x}function c(m){var q=fa(ha);ha[q]=m;return q}function e(m){return m.naturalHeight||m.videoHeight||m.displayHeight||m.height}function f(m){return m.naturalWidth||m.videoWidth||m.displayWidth||m.width}function k(m,q,x,y){m.bindTexture(m.TEXTURE_2D,q);y||x.alphaType!==a.AlphaType.Premul||m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return q}function l(m,q,x){x||q.alphaType!==a.AlphaType.Premul||
m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);m.bindTexture(m.TEXTURE_2D,null)}a.GetWebGLContext=function(m,q){if(!m)throw"null canvas passed into makeWebGLContext";var x={alpha:b(q,"alpha",1),depth:b(q,"depth",1),stencil:b(q,"stencil",8),antialias:b(q,"antialias",0),premultipliedAlpha:b(q,"premultipliedAlpha",1),preserveDrawingBuffer:b(q,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(q,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(q,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(q,"enableExtensionsByDefault",1),explicitSwapControl:b(q,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(q,"renderViaOffscreenBackBuffer",0)};x.majorVersion=q&&q.majorVersion?q.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(x.explicitSwapControl)throw"explicitSwapControl is not supported";m=ia(m,x);if(!m)return 0;ja(m);t.$d.getExtension("WEBGL_debug_renderer_info");return m};a.deleteContext=function(m){t===ka[m]&&(t=null);"object"===typeof JSEvents&&
JSEvents.Of(ka[m].$d.canvas);ka[m]&&ka[m].$d.canvas&&(ka[m].$d.canvas.Re=void 0);ka[m]=null};a._setTextureCleanup({deleteTexture:function(m,q){var x=ha[q];x&&ka[m].$d.deleteTexture(x);ha[q]=null}});a.MakeWebGLContext=function(m){if(!this.Pd(m))return null;var q=this._MakeGrContext();if(!q)return null;q.Od=m;var x=q.delete.bind(q);q["delete"]=function(){a.Pd(this.Od);x()}.bind(q);return t.De=q};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.Pd(this.Od);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.Pd(this.Od);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.Pd(this.Od);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(m){a.Pd(this.Od);this._setResourceCacheLimitBytes(m)};a.MakeOnScreenGLSurface=function(m,q,x,y,C,E){if(!this.Pd(m.Od))return null;q=void 0===C||void 0===E?
this._MakeOnScreenGLSurface(m,q,x,y):this._MakeOnScreenGLSurface(m,q,x,y,C,E);if(!q)return null;q.Od=m.Od;return q};a.MakeRenderTarget=function(){var m=arguments[0];if(!this.Pd(m.Od))return null;if(3===arguments.length){var q=this._MakeRenderTargetWH(m,arguments[1],arguments[2]);if(!q)return null}else if(2===arguments.length){if(q=this._MakeRenderTargetII(m,arguments[1]),!q)return null}else return null;q.Od=m.Od;return q};a.MakeWebGLCanvasSurface=function(m,q,x){q=q||null;var y=m,C="undefined"!==
typeof OffscreenCanvas&&y instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&y instanceof HTMLCanvasElement||C||(y=document.getElementById(m),y)))throw"Canvas with id "+m+" was not found";m=this.GetWebGLContext(y,x);if(!m||0>m)throw"failed to create webgl context: err "+m;m=this.MakeWebGLContext(m);q=this.MakeOnScreenGLSurface(m,y.width,y.height,q);return q?q:(q=y.cloneNode(!0),y.parentNode.replaceChild(q,y),q.classList.add("ck-replaced"),a.MakeSWCanvasSurface(q))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(m,q){a.Pd(this.Od);m=c(m);if(q=this._makeImageFromTexture(this.Od,m,q))q.ke=m;return q};a.Surface.prototype.makeImageFromTextureSource=function(m,q,x){q||(q={height:e(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);a.Pd(this.Od);var y=t.$d;x=k(y,y.createTexture(),q,x);2===t.version?y.texImage2D(y.TEXTURE_2D,0,y.RGBA,q.width,q.height,
0,y.RGBA,y.UNSIGNED_BYTE,m):y.texImage2D(y.TEXTURE_2D,0,y.RGBA,y.RGBA,y.UNSIGNED_BYTE,m);l(y,q);this._resetContext();return this.makeImageFromTexture(x,q)};a.Surface.prototype.updateTextureFromSource=function(m,q,x){if(m.ke){a.Pd(this.Od);var y=m.getImageInfo(),C=t.$d,E=k(C,ha[m.ke],y,x);2===t.version?C.texImage2D(C.TEXTURE_2D,0,C.RGBA,f(q),e(q),0,C.RGBA,C.UNSIGNED_BYTE,q):C.texImage2D(C.TEXTURE_2D,0,C.RGBA,C.RGBA,C.UNSIGNED_BYTE,q);l(C,y,x);this._resetContext();ha[m.ke]=null;m.ke=c(E);y.colorSpace=
m.getColorSpace();q=this._makeImageFromTexture(this.Od,m.ke,y);x=m.Nd.Qd;C=m.Nd.Vd;m.Nd.Qd=q.Nd.Qd;m.Nd.Vd=q.Nd.Vd;q.Nd.Qd=x;q.Nd.Vd=C;q.delete();y.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(m,q,x){q||(q={height:e(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);var y={makeTexture:function(){var C=t,E=C.$d,v=k(E,E.createTexture(),q,x);2===C.version?E.texImage2D(E.TEXTURE_2D,0,E.RGBA,
q.width,q.height,0,E.RGBA,E.UNSIGNED_BYTE,m):E.texImage2D(E.TEXTURE_2D,0,E.RGBA,E.RGBA,E.UNSIGNED_BYTE,m);l(E,q,x);return c(v)},freeSrc:function(){}};"VideoFrame"===m.constructor.name&&(y.freeSrc=function(){m.close()});return a.Image._makeFromGenerator(q,y)};a.Pd=function(m){return m?ja(m):!1};a.re=function(){return t&&t.De&&!t.De.isDeleted()?t.De:null}})})(r);
(function(a){function b(g){return(f(255*g[3])<<24|f(255*g[0])<<16|f(255*g[1])<<8|f(255*g[2])<<0)>>>0}function c(g){if(g&&g._ck)return g;if(g instanceof Float32Array){for(var d=Math.floor(g.length/4),h=new Uint32Array(d),n=0;n<d;n++)h[n]=b(g.slice(4*n,4*(n+1)));return h}if(g instanceof Uint32Array)return g;if(g instanceof Array&&g[0]instanceof Float32Array)return g.map(b)}function e(g){if(void 0===g)return 1;var d=parseFloat(g);return g&&-1!==g.indexOf("%")?d/100:d}function f(g){return Math.round(Math.max(0,
Math.min(g||0,255)))}function k(g,d){d&&d._ck||a._free(g)}function l(g,d,h){if(!g||!g.length)return M;if(g&&g._ck)return g.byteOffset;var n=a[d].BYTES_PER_ELEMENT;h||(h=a._malloc(g.length*n));a[d].set(g,h/n);return h}function m(g){var d={Xd:M,count:g.length,le:a.ColorType.RGBA_F32};if(g instanceof Float32Array)d.Xd=l(g,"HEAPF32"),d.count=g.length/4;else if(g instanceof Uint32Array)d.Xd=l(g,"HEAPU32"),d.le=a.ColorType.RGBA_8888;else if(g instanceof Array){if(g&&g.length){for(var h=a._malloc(16*g.length),
n=0,u=h/4,w=0;w<g.length;w++)for(var z=0;4>z;z++)a.HEAPF32[u+n]=g[w][z],n++;g=h}else g=M;d.Xd=g}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof g;return d}function q(g){if(!g)return M;var d=R.toTypedArray();if(g.length){if(6===g.length||9===g.length)return l(g,"HEAPF32",I),6===g.length&&a.HEAPF32.set(md,6+I/4),I;if(16===g.length)return d[0]=g[0],d[1]=g[1],d[2]=g[3],d[3]=g[4],d[4]=g[5],d[5]=g[7],d[6]=g[12],d[7]=g[13],d[8]=g[15],I;throw"invalid matrix size";}if(void 0===
g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m41;d[3]=g.m12;d[4]=g.m22;d[5]=g.m42;d[6]=g.m14;d[7]=g.m24;d[8]=g.m44;return I}function x(g){if(!g)return M;var d=da.toTypedArray();if(g.length){if(16!==g.length&&6!==g.length&&9!==g.length)throw"invalid matrix size";if(16===g.length)return l(g,"HEAPF32",ca);d.fill(0);d[0]=g[0];d[1]=g[1];d[3]=g[2];d[4]=g[3];d[5]=g[4];d[7]=g[5];d[10]=1;d[12]=g[6];d[13]=g[7];d[15]=g[8];6===g.length&&(d[12]=0,d[13]=0,d[15]=1);return ca}if(void 0===g.m11)throw"invalid matrix argument";
d[0]=g.m11;d[1]=g.m21;d[2]=g.m31;d[3]=g.m41;d[4]=g.m12;d[5]=g.m22;d[6]=g.m32;d[7]=g.m42;d[8]=g.m13;d[9]=g.m23;d[10]=g.m33;d[11]=g.m43;d[12]=g.m14;d[13]=g.m24;d[14]=g.m34;d[15]=g.m44;return ca}function y(g,d){return l(g,"HEAPF32",d||ua)}function C(g,d,h,n){var u=Ma.toTypedArray();u[0]=g;u[1]=d;u[2]=h;u[3]=n;return ua}function E(g){for(var d=new Float32Array(4),h=0;4>h;h++)d[h]=a.HEAPF32[g/4+h];return d}function v(g,d){return l(g,"HEAPF32",d||W)}function D(g,d){return l(g,"HEAPF32",d||Gb)}a.Color=function(g,
d,h,n){void 0===n&&(n=1);return a.Color4f(f(g)/255,f(d)/255,f(h)/255,n)};a.ColorAsInt=function(g,d,h,n){void 0===n&&(n=255);return(f(n)<<24|f(g)<<16|f(d)<<8|f(h)<<0&268435455)>>>0};a.Color4f=function(g,d,h,n){void 0===n&&(n=1);return Float32Array.of(g,d,h,n)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,1,1,1)}});Object.defineProperty(a,
"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(g){return[Math.floor(255*g[0]),Math.floor(255*
g[1]),Math.floor(255*g[2]),g[3]]};a.parseColorString=function(g,d){g=g.toLowerCase();if(g.startsWith("#")){d=255;switch(g.length){case 9:d=parseInt(g.slice(7,9),16);case 7:var h=parseInt(g.slice(1,3),16);var n=parseInt(g.slice(3,5),16);var u=parseInt(g.slice(5,7),16);break;case 5:d=17*parseInt(g.slice(4,5),16);case 4:h=17*parseInt(g.slice(1,2),16),n=17*parseInt(g.slice(2,3),16),u=17*parseInt(g.slice(3,4),16)}return a.Color(h,n,u,d/255)}return g.startsWith("rgba")?(g=g.slice(5,-1),g=g.split(","),a.Color(+g[0],
+g[1],+g[2],e(g[3]))):g.startsWith("rgb")?(g=g.slice(4,-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("gray(")||g.startsWith("hsl")||!d||(g=d[g],void 0===g)?a.BLACK:g};a.multiplyByAlpha=function(g,d){g=g.slice();g[3]=Math.max(0,Math.min(g[3]*d,1));return g};a.Malloc=function(g,d){var h=a._malloc(d*g.BYTES_PER_ELEMENT);return{_ck:!0,length:d,byteOffset:h,de:null,subarray:function(n,u){n=this.toTypedArray().subarray(n,u);n._ck=!0;return n},toTypedArray:function(){if(this.de&&this.de.length)return this.de;
this.de=new g(a.HEAPU8.buffer,h,d);this.de._ck=!0;return this.de}}};a.Free=function(g){a._free(g.byteOffset);g.byteOffset=M;g.toTypedArray=null;g.de=null};var I=M,R,ca=M,da,ua=M,Ma,va,W=M,nc,Aa=M,oc,Hb=M,pc,Ib=M,Jb,gb=M,qc,Gb=M,rc,sc=M,md=Float32Array.of(0,0,1),M=0;a.onRuntimeInitialized=function(){function g(d,h,n,u,w,z,F){z||(z=4*u.width,u.colorType===a.ColorType.RGBA_F16?z*=2:u.colorType===a.ColorType.RGBA_F32&&(z*=4));var K=z*u.height;var H=w?w.byteOffset:a._malloc(K);if(F?!d._readPixels(u,H,
z,h,n,F):!d._readPixels(u,H,z,h,n))return w||a._free(H),null;if(w)return w.toTypedArray();switch(u.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:d=(new Uint8Array(a.HEAPU8.buffer,H,K)).slice();break;case a.ColorType.RGBA_F32:d=(new Float32Array(a.HEAPU8.buffer,H,K)).slice();break;default:return null}a._free(H);return d}Ma=a.Malloc(Float32Array,4);ua=Ma.byteOffset;da=a.Malloc(Float32Array,16);ca=da.byteOffset;R=a.Malloc(Float32Array,9);I=R.byteOffset;qc=a.Malloc(Float32Array,12);
Gb=qc.byteOffset;rc=a.Malloc(Float32Array,12);sc=rc.byteOffset;va=a.Malloc(Float32Array,4);W=va.byteOffset;nc=a.Malloc(Float32Array,4);Aa=nc.byteOffset;oc=a.Malloc(Float32Array,3);Hb=oc.byteOffset;pc=a.Malloc(Float32Array,3);Ib=pc.byteOffset;Jb=a.Malloc(Int32Array,4);gb=Jb.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(d){var h=l(d,"HEAPF32"),n=a.Path._MakeFromCmds(h,d.length);k(h,d);return n};a.Path.MakeFromVerbsPointsWeights=function(d,h,n){var u=l(d,"HEAPU8"),w=l(h,"HEAPF32"),z=l(n,"HEAPF32"),F=a.Path._MakeFromVerbsPointsWeights(u,d.length,w,h.length,z,n&&n.length||0);k(u,d);k(w,h);k(z,n);return F};a.Path.prototype.addArc=function(d,h,n){d=v(d);this._addArc(d,h,n);return this};a.Path.prototype.addCircle=function(d,h,n,u){this._addCircle(d,h,n,!!u);return this};a.Path.prototype.addOval=function(d,h,n){void 0===
n&&(n=1);d=v(d);this._addOval(d,!!h,n);return this};a.Path.prototype.addPath=function(){var d=Array.prototype.slice.call(arguments),h=d[0],n=!1;"boolean"===typeof d[d.length-1]&&(n=d.pop());if(1===d.length)this._addPath(h,1,0,0,0,1,0,0,0,1,n);else if(2===d.length)d=d[1],this._addPath(h,d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1,n);else if(7===d.length||10===d.length)this._addPath(h,d[1],d[2],d[3],d[4],d[5],d[6],d[7]||0,d[8]||0,d[9]||1,n);else return null;return this};a.Path.prototype.addPoly=
function(d,h){var n=l(d,"HEAPF32");this._addPoly(n,d.length/2,h);k(n,d);return this};a.Path.prototype.addRect=function(d,h){d=v(d);this._addRect(d,!!h);return this};a.Path.prototype.addRRect=function(d,h){d=D(d);this._addRRect(d,!!h);return this};a.Path.prototype.addVerbsPointsWeights=function(d,h,n){var u=l(d,"HEAPU8"),w=l(h,"HEAPF32"),z=l(n,"HEAPF32");this._addVerbsPointsWeights(u,d.length,w,h.length,z,n&&n.length||0);k(u,d);k(w,h);k(z,n)};a.Path.prototype.arc=function(d,h,n,u,w,z){d=a.LTRBRect(d-
n,h-n,d+n,h+n);w=(w-u)/Math.PI*180-360*!!z;z=new a.Path;z.addArc(d,u/Math.PI*180,w);this.addPath(z,!0);z.delete();return this};a.Path.prototype.arcToOval=function(d,h,n,u){d=v(d);this._arcToOval(d,h,n,u);return this};a.Path.prototype.arcToRotated=function(d,h,n,u,w,z,F){this._arcToRotated(d,h,n,!!u,!!w,z,F);return this};a.Path.prototype.arcToTangent=function(d,h,n,u,w){this._arcToTangent(d,h,n,u,w);return this};a.Path.prototype.close=function(){this._close();return this};a.Path.prototype.conicTo=
function(d,h,n,u,w){this._conicTo(d,h,n,u,w);return this};a.Path.prototype.computeTightBounds=function(d){this._computeTightBounds(W);var h=va.toTypedArray();return d?(d.set(h),d):h.slice()};a.Path.prototype.cubicTo=function(d,h,n,u,w,z){this._cubicTo(d,h,n,u,w,z);return this};a.Path.prototype.dash=function(d,h,n){return this._dash(d,h,n)?this:null};a.Path.prototype.getBounds=function(d){this._getBounds(W);var h=va.toTypedArray();return d?(d.set(h),d):h.slice()};a.Path.prototype.lineTo=function(d,
h){this._lineTo(d,h);return this};a.Path.prototype.moveTo=function(d,h){this._moveTo(d,h);return this};a.Path.prototype.offset=function(d,h){this._transform(1,0,d,0,1,h,0,0,1);return this};a.Path.prototype.quadTo=function(d,h,n,u){this._quadTo(d,h,n,u);return this};a.Path.prototype.rArcTo=function(d,h,n,u,w,z,F){this._rArcTo(d,h,n,u,w,z,F);return this};a.Path.prototype.rConicTo=function(d,h,n,u,w){this._rConicTo(d,h,n,u,w);return this};a.Path.prototype.rCubicTo=function(d,h,n,u,w,z){this._rCubicTo(d,
h,n,u,w,z);return this};a.Path.prototype.rLineTo=function(d,h){this._rLineTo(d,h);return this};a.Path.prototype.rMoveTo=function(d,h){this._rMoveTo(d,h);return this};a.Path.prototype.rQuadTo=function(d,h,n,u){this._rQuadTo(d,h,n,u);return this};a.Path.prototype.stroke=function(d){d=d||{};d.width=d.width||1;d.miter_limit=d.miter_limit||4;d.cap=d.cap||a.StrokeCap.Butt;d.join=d.join||a.StrokeJoin.Miter;d.precision=d.precision||1;return this._stroke(d)?this:null};a.Path.prototype.transform=function(){if(1===
arguments.length){var d=arguments[0];this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1)}else if(6===arguments.length||9===arguments.length)d=arguments,this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.trim=function(d,h,n){return this._trim(d,h,!!n)?this:null};a.Image.prototype.encodeToBytes=function(d,h){var n=a.re();d=d||a.ImageFormat.PNG;h=h||100;
return n?this._encodeToBytes(d,h,n):this._encodeToBytes(d,h)};a.Image.prototype.makeShaderCubic=function(d,h,n,u,w){w=q(w);return this._makeShaderCubic(d,h,n,u,w)};a.Image.prototype.makeShaderOptions=function(d,h,n,u,w){w=q(w);return this._makeShaderOptions(d,h,n,u,w)};a.Image.prototype.readPixels=function(d,h,n,u,w){var z=a.re();return g(this,d,h,n,u,w,z)};a.Canvas.prototype.clear=function(d){a.Pd(this.Od);d=y(d);this._clear(d)};a.Canvas.prototype.clipRRect=function(d,h,n){a.Pd(this.Od);d=D(d);this._clipRRect(d,
h,n)};a.Canvas.prototype.clipRect=function(d,h,n){a.Pd(this.Od);d=v(d);this._clipRect(d,h,n)};a.Canvas.prototype.concat=function(d){a.Pd(this.Od);d=x(d);this._concat(d)};a.Canvas.prototype.drawArc=function(d,h,n,u,w){a.Pd(this.Od);d=v(d);this._drawArc(d,h,n,u,w)};a.Canvas.prototype.drawAtlas=function(d,h,n,u,w,z,F){if(d&&u&&h&&n&&h.length===n.length){a.Pd(this.Od);w||(w=a.BlendMode.SrcOver);var K=l(h,"HEAPF32"),H=l(n,"HEAPF32"),S=n.length/4,p=l(c(z),"HEAPU32");if(F&&"B"in F&&"C"in F)this._drawAtlasCubic(d,
H,K,p,S,w,F.B,F.C,u);else{let A=a.FilterMode.Linear,L=a.MipmapMode.None;F&&(A=F.filter,"mipmap"in F&&(L=F.mipmap));this._drawAtlasOptions(d,H,K,p,S,w,A,L,u)}k(K,h);k(H,n);k(p,z)}};a.Canvas.prototype.drawCircle=function(d,h,n,u){a.Pd(this.Od);this._drawCircle(d,h,n,u)};a.Canvas.prototype.drawColor=function(d,h){a.Pd(this.Od);d=y(d);void 0!==h?this._drawColor(d,h):this._drawColor(d)};a.Canvas.prototype.drawColorInt=function(d,h){a.Pd(this.Od);this._drawColorInt(d,h||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=
function(d,h,n,u,w){a.Pd(this.Od);d=C(d,h,n,u);void 0!==w?this._drawColor(d,w):this._drawColor(d)};a.Canvas.prototype.drawDRRect=function(d,h,n){a.Pd(this.Od);d=D(d,Gb);h=D(h,sc);this._drawDRRect(d,h,n)};a.Canvas.prototype.drawImage=function(d,h,n,u){a.Pd(this.Od);this._drawImage(d,h,n,u||null)};a.Canvas.prototype.drawImageCubic=function(d,h,n,u,w,z){a.Pd(this.Od);this._drawImageCubic(d,h,n,u,w,z||null)};a.Canvas.prototype.drawImageOptions=function(d,h,n,u,w,z){a.Pd(this.Od);this._drawImageOptions(d,
h,n,u,w,z||null)};a.Canvas.prototype.drawImageNine=function(d,h,n,u,w){a.Pd(this.Od);h=l(h,"HEAP32",gb);n=v(n);this._drawImageNine(d,h,n,u,w||null)};a.Canvas.prototype.drawImageRect=function(d,h,n,u,w){a.Pd(this.Od);v(h,W);v(n,Aa);this._drawImageRect(d,W,Aa,u,!!w)};a.Canvas.prototype.drawImageRectCubic=function(d,h,n,u,w,z){a.Pd(this.Od);v(h,W);v(n,Aa);this._drawImageRectCubic(d,W,Aa,u,w,z||null)};a.Canvas.prototype.drawImageRectOptions=function(d,h,n,u,w,z){a.Pd(this.Od);v(h,W);v(n,Aa);this._drawImageRectOptions(d,
W,Aa,u,w,z||null)};a.Canvas.prototype.drawLine=function(d,h,n,u,w){a.Pd(this.Od);this._drawLine(d,h,n,u,w)};a.Canvas.prototype.drawOval=function(d,h){a.Pd(this.Od);d=v(d);this._drawOval(d,h)};a.Canvas.prototype.drawPaint=function(d){a.Pd(this.Od);this._drawPaint(d)};a.Canvas.prototype.drawParagraph=function(d,h,n){a.Pd(this.Od);this._drawParagraph(d,h,n)};a.Canvas.prototype.drawPatch=function(d,h,n,u,w){if(24>d.length)throw"Need 12 cubic points";if(h&&4>h.length)throw"Need 4 colors";if(n&&8>n.length)throw"Need 4 shader coordinates";
a.Pd(this.Od);const z=l(d,"HEAPF32"),F=h?l(c(h),"HEAPU32"):M,K=n?l(n,"HEAPF32"):M;u||(u=a.BlendMode.Modulate);this._drawPatch(z,F,K,u,w);k(K,n);k(F,h);k(z,d)};a.Canvas.prototype.drawPath=function(d,h){a.Pd(this.Od);this._drawPath(d,h)};a.Canvas.prototype.drawPicture=function(d){a.Pd(this.Od);this._drawPicture(d)};a.Canvas.prototype.drawPoints=function(d,h,n){a.Pd(this.Od);var u=l(h,"HEAPF32");this._drawPoints(d,u,h.length/2,n);k(u,h)};a.Canvas.prototype.drawRRect=function(d,h){a.Pd(this.Od);d=D(d);
this._drawRRect(d,h)};a.Canvas.prototype.drawRect=function(d,h){a.Pd(this.Od);d=v(d);this._drawRect(d,h)};a.Canvas.prototype.drawRect4f=function(d,h,n,u,w){a.Pd(this.Od);this._drawRect4f(d,h,n,u,w)};a.Canvas.prototype.drawShadow=function(d,h,n,u,w,z,F){a.Pd(this.Od);var K=l(w,"HEAPF32"),H=l(z,"HEAPF32");h=l(h,"HEAPF32",Hb);n=l(n,"HEAPF32",Ib);this._drawShadow(d,h,n,u,K,H,F);k(K,w);k(H,z)};a.getShadowLocalBounds=function(d,h,n,u,w,z,F){d=q(d);n=l(n,"HEAPF32",Hb);u=l(u,"HEAPF32",Ib);if(!this._getShadowLocalBounds(d,
h,n,u,w,z,W))return null;h=va.toTypedArray();return F?(F.set(h),F):h.slice()};a.Canvas.prototype.drawTextBlob=function(d,h,n,u){a.Pd(this.Od);this._drawTextBlob(d,h,n,u)};a.Canvas.prototype.drawVertices=function(d,h,n){a.Pd(this.Od);this._drawVertices(d,h,n)};a.Canvas.prototype.getDeviceClipBounds=function(d){this._getDeviceClipBounds(gb);var h=Jb.toTypedArray();d?d.set(h):d=h.slice();return d};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(ca);for(var d=ca,h=Array(16),n=0;16>
n;n++)h[n]=a.HEAPF32[d/4+n];return h};a.Canvas.prototype.getTotalMatrix=function(){this._getTotalMatrix(I);for(var d=Array(9),h=0;9>h;h++)d[h]=a.HEAPF32[I/4+h];return d};a.Canvas.prototype.makeSurface=function(d){d=this._makeSurface(d);d.Od=this.Od;return d};a.Canvas.prototype.readPixels=function(d,h,n,u,w){a.Pd(this.Od);return g(this,d,h,n,u,w)};a.Canvas.prototype.saveLayer=function(d,h,n,u){h=v(h);return this._saveLayer(d||null,h,n||null,u||0)};a.Canvas.prototype.writePixels=function(d,h,n,u,w,
z,F,K){if(d.byteLength%(h*n))throw"pixels length must be a multiple of the srcWidth * srcHeight";a.Pd(this.Od);var H=d.byteLength/(h*n);z=z||a.AlphaType.Unpremul;F=F||a.ColorType.RGBA_8888;K=K||a.ColorSpace.SRGB;var S=H*h;H=l(d,"HEAPU8");h=this._writePixels({width:h,height:n,colorType:F,alphaType:z,colorSpace:K},H,S,u,w);k(H,d);return h};a.ColorFilter.MakeBlend=function(d,h,n){d=y(d);n=n||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(d,h,n)};a.ColorFilter.MakeMatrix=function(d){if(!d||20!==d.length)throw"invalid color matrix";
var h=l(d,"HEAPF32"),n=a.ColorFilter._makeMatrix(h);k(h,d);return n};a.ContourMeasure.prototype.getPosTan=function(d,h){this._getPosTan(d,W);d=va.toTypedArray();return h?(h.set(d),h):d.slice()};a.ImageFilter.MakeDropShadow=function(d,h,n,u,w,z){w=y(w,ua);return a.ImageFilter._MakeDropShadow(d,h,n,u,w,z)};a.ImageFilter.MakeDropShadowOnly=function(d,h,n,u,w,z){w=y(w,ua);return a.ImageFilter._MakeDropShadowOnly(d,h,n,u,w,z)};a.ImageFilter.MakeImage=function(d,h,n,u){n=v(n,W);u=v(u,Aa);if("B"in h&&"C"in
h)return a.ImageFilter._MakeImageCubic(d,h.B,h.C,n,u);const w=h.filter;let z=a.MipmapMode.None;"mipmap"in h&&(z=h.mipmap);return a.ImageFilter._MakeImageOptions(d,w,z,n,u)};a.ImageFilter.MakeMatrixTransform=function(d,h,n){d=q(d);if("B"in h&&"C"in h)return a.ImageFilter._MakeMatrixTransformCubic(d,h.B,h.C,n);const u=h.filter;let w=a.MipmapMode.None;"mipmap"in h&&(w=h.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(d,u,w,n)};a.Paint.prototype.getColor=function(){this._getColor(ua);return E(ua)};
a.Paint.prototype.setColor=function(d,h){h=h||null;d=y(d);this._setColor(d,h)};a.Paint.prototype.setColorComponents=function(d,h,n,u,w){w=w||null;d=C(d,h,n,u);this._setColor(d,w)};a.Path.prototype.getPoint=function(d,h){this._getPoint(d,W);d=va.toTypedArray();return h?(h[0]=d[0],h[1]=d[1],h):d.slice(0,2)};a.Picture.prototype.makeShader=function(d,h,n,u,w){u=q(u);w=v(w);return this._makeShader(d,h,n,u,w)};a.PictureRecorder.prototype.beginRecording=function(d){d=v(d);return this._beginRecording(d)};
a.Surface.prototype.getCanvas=function(){var d=this._getCanvas();d.Od=this.Od;return d};a.Surface.prototype.makeImageSnapshot=function(d){a.Pd(this.Od);d=l(d,"HEAP32",gb);return this._makeImageSnapshot(d)};a.Surface.prototype.makeSurface=function(d){a.Pd(this.Od);d=this._makeSurface(d);d.Od=this.Od;return d};a.Surface.prototype.Ve=function(d,h){this.je||(this.je=this.getCanvas());return requestAnimationFrame(function(){a.Pd(this.Od);d(this.je);this.flush(h)}.bind(this))};a.Surface.prototype.requestAnimationFrame||
(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.Ve);a.Surface.prototype.Se=function(d,h){this.je||(this.je=this.getCanvas());requestAnimationFrame(function(){a.Pd(this.Od);d(this.je);this.flush(h);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.Se);a.PathEffect.MakeDash=function(d,h){h||(h=0);if(!d.length||1===d.length%2)throw"Intervals array must have even length";var n=l(d,"HEAPF32");h=a.PathEffect._MakeDash(n,d.length,
h);k(n,d);return h};a.PathEffect.MakeLine2D=function(d,h){h=q(h);return a.PathEffect._MakeLine2D(d,h)};a.PathEffect.MakePath2D=function(d,h){d=q(d);return a.PathEffect._MakePath2D(d,h)};a.Shader.MakeColor=function(d,h){h=h||null;d=y(d);return a.Shader._MakeColor(d,h)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;a.Shader.MakeLinearGradient=function(d,h,n,u,w,z,F,K){K=K||null;var H=m(n),S=l(u,"HEAPF32");F=F||0;z=q(z);var p=va.toTypedArray();p.set(d);p.set(h,2);d=a.Shader._MakeLinearGradient(W,
H.Xd,H.le,S,H.count,w,F,z,K);k(H.Xd,n);u&&k(S,u);return d};a.Shader.MakeRadialGradient=function(d,h,n,u,w,z,F,K){K=K||null;var H=m(n),S=l(u,"HEAPF32");F=F||0;z=q(z);d=a.Shader._MakeRadialGradient(d[0],d[1],h,H.Xd,H.le,S,H.count,w,F,z,K);k(H.Xd,n);u&&k(S,u);return d};a.Shader.MakeSweepGradient=function(d,h,n,u,w,z,F,K,H,S){S=S||null;var p=m(n),A=l(u,"HEAPF32");F=F||0;K=K||0;H=H||360;z=q(z);d=a.Shader._MakeSweepGradient(d,h,p.Xd,p.le,A,p.count,w,K,H,F,z,S);k(p.Xd,n);u&&k(A,u);return d};a.Shader.MakeTwoPointConicalGradient=
function(d,h,n,u,w,z,F,K,H,S){S=S||null;var p=m(w),A=l(z,"HEAPF32");H=H||0;K=q(K);var L=va.toTypedArray();L.set(d);L.set(n,2);d=a.Shader._MakeTwoPointConicalGradient(W,h,u,p.Xd,p.le,A,p.count,F,H,K,S);k(p.Xd,w);z&&k(A,z);return d};a.Vertices.prototype.bounds=function(d){this._bounds(W);var h=va.toTypedArray();return d?(d.set(h),d):h.slice()};a.Sd&&a.Sd.forEach(function(d){d()})};a.computeTonalColors=function(g){var d=l(g.ambient,"HEAPF32"),h=l(g.spot,"HEAPF32");this._computeTonalColors(d,h);var n=
{ambient:E(d),spot:E(h)};k(d,g.ambient);k(h,g.spot);return n};a.LTRBRect=function(g,d,h,n){return Float32Array.of(g,d,h,n)};a.XYWHRect=function(g,d,h,n){return Float32Array.of(g,d,g+h,d+n)};a.LTRBiRect=function(g,d,h,n){return Int32Array.of(g,d,h,n)};a.XYWHiRect=function(g,d,h,n){return Int32Array.of(g,d,g+h,d+n)};a.RRectXY=function(g,d,h){return Float32Array.of(g[0],g[1],g[2],g[3],d,h,d,h,d,h,d,h)};a.MakeAnimatedImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,
d);return(g=a._decodeAnimatedImage(d,g.byteLength))?g:null};a.MakeImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeImage(d,g.byteLength))?g:null};var Ra=null;a.MakeImageFromCanvasImageSource=function(g){var d=g.width,h=g.height;Ra||(Ra=document.createElement("canvas"));Ra.width=d;Ra.height=h;var n=Ra.getContext("2d",{Qf:!0});n.drawImage(g,0,0);g=n.getImageData(0,0,d,h);return a.MakeImage({width:d,height:h,alphaType:a.AlphaType.Unpremul,
colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},g.data,4*d)};a.MakeImage=function(g,d,h){var n=a._malloc(d.length);a.HEAPU8.set(d,n);return a._MakeImage(g,n,d.length,h)};a.MakeVertices=function(g,d,h,n,u,w){var z=u&&u.length||0,F=0;h&&h.length&&(F|=1);n&&n.length&&(F|=2);void 0===w||w||(F|=4);g=new a._VerticesBuilder(g,d.length/2,z,F);l(d,"HEAPF32",g.positions());g.texCoords()&&l(h,"HEAPF32",g.texCoords());g.colors()&&l(c(n),"HEAPU32",g.colors());g.indices()&&l(u,"HEAPU16",g.indices());
return g.detach()};(function(g){g.Sd=g.Sd||[];g.Sd.push(function(){function d(p){if(!p||!p.length)return[];for(var A=[],L=0;L<p.length;L+=5){var V=g.LTRBRect(p[L],p[L+1],p[L+2],p[L+3]),za=g.TextDirection.LTR;0===p[L+4]&&(za=g.TextDirection.RTL);A.push({rect:V,dir:za})}g._free(p.byteOffset);return A}function h(p){p=p||{};void 0===p.weight&&(p.weight=g.FontWeight.Normal);p.width=p.width||g.FontWidth.Normal;p.slant=p.slant||g.FontSlant.Upright;return p}function n(p){if(!p||!p.length)return M;for(var A=
[],L=0;L<p.length;L++){var V=u(p[L]);A.push(V)}return l(A,"HEAPU32")}function u(p){if(F[p])return F[p];var A=la(p)+1,L=g._malloc(A);ma(p,B,L,A);return F[p]=L}function w(p){p._colorPtr=y(p.color);p._foregroundColorPtr=M;p._backgroundColorPtr=M;p._decorationColorPtr=M;p.foregroundColor&&(p._foregroundColorPtr=y(p.foregroundColor,K));p.backgroundColor&&(p._backgroundColorPtr=y(p.backgroundColor,H));p.decorationColor&&(p._decorationColorPtr=y(p.decorationColor,S));Array.isArray(p.fontFamilies)&&p.fontFamilies.length?
(p._fontFamiliesPtr=n(p.fontFamilies),p._fontFamiliesLen=p.fontFamilies.length):(p._fontFamiliesPtr=M,p._fontFamiliesLen=0);if(p.locale){var A=p.locale;p._localePtr=u(A);p._localeLen=la(A)+1}else p._localePtr=M,p._localeLen=0;if(Array.isArray(p.shadows)&&p.shadows.length){A=p.shadows;var L=A.map(function(pa){return pa.color||g.BLACK}),V=A.map(function(pa){return pa.blurRadius||0});p._shadowLen=A.length;for(var za=g._malloc(8*A.length),Kb=za/4,Lb=0;Lb<A.length;Lb++){var tc=A[Lb].offset||[0,0];g.HEAPF32[Kb]=
tc[0];g.HEAPF32[Kb+1]=tc[1];Kb+=2}p._shadowColorsPtr=m(L).Xd;p._shadowOffsetsPtr=za;p._shadowBlurRadiiPtr=l(V,"HEAPF32")}else p._shadowLen=0,p._shadowColorsPtr=M,p._shadowOffsetsPtr=M,p._shadowBlurRadiiPtr=M;Array.isArray(p.fontFeatures)&&p.fontFeatures.length?(A=p.fontFeatures,L=A.map(function(pa){return pa.name}),V=A.map(function(pa){return pa.value}),p._fontFeatureLen=A.length,p._fontFeatureNamesPtr=n(L),p._fontFeatureValuesPtr=l(V,"HEAPU32")):(p._fontFeatureLen=0,p._fontFeatureNamesPtr=M,p._fontFeatureValuesPtr=
M);Array.isArray(p.fontVariations)&&p.fontVariations.length?(A=p.fontVariations,L=A.map(function(pa){return pa.axis}),V=A.map(function(pa){return pa.value}),p._fontVariationLen=A.length,p._fontVariationAxesPtr=n(L),p._fontVariationValuesPtr=l(V,"HEAPF32")):(p._fontVariationLen=0,p._fontVariationAxesPtr=M,p._fontVariationValuesPtr=M)}function z(p){g._free(p._fontFamiliesPtr);g._free(p._shadowColorsPtr);g._free(p._shadowOffsetsPtr);g._free(p._shadowBlurRadiiPtr);g._free(p._fontFeatureNamesPtr);g._free(p._fontFeatureValuesPtr);
g._free(p._fontVariationAxesPtr);g._free(p._fontVariationValuesPtr)}g.Paragraph.prototype.getRectsForRange=function(p,A,L,V){p=this._getRectsForRange(p,A,L,V);return d(p)};g.Paragraph.prototype.getRectsForPlaceholders=function(){var p=this._getRectsForPlaceholders();return d(p)};g.TypefaceFontProvider.prototype.registerFont=function(p,A){p=g.Typeface.MakeFreeTypeFaceFromData(p);if(!p)return null;A=u(A);this._registerFont(p,A)};g.ParagraphStyle=function(p){p.disableHinting=p.disableHinting||!1;if(p.ellipsis){var A=
p.ellipsis;p._ellipsisPtr=u(A);p._ellipsisLen=la(A)+1}else p._ellipsisPtr=M,p._ellipsisLen=0;null==p.heightMultiplier&&(p.heightMultiplier=-1);p.maxLines=p.maxLines||0;p.replaceTabCharacters=p.replaceTabCharacters||!1;A=(A=p.strutStyle)||{};A.strutEnabled=A.strutEnabled||!1;A.strutEnabled&&Array.isArray(A.fontFamilies)&&A.fontFamilies.length?(A._fontFamiliesPtr=n(A.fontFamilies),A._fontFamiliesLen=A.fontFamilies.length):(A._fontFamiliesPtr=M,A._fontFamiliesLen=0);A.fontStyle=h(A.fontStyle);null==
A.fontSize&&(A.fontSize=-1);null==A.heightMultiplier&&(A.heightMultiplier=-1);A.halfLeading=A.halfLeading||!1;A.leading=A.leading||0;A.forceStrutHeight=A.forceStrutHeight||!1;p.strutStyle=A;p.textAlign=p.textAlign||g.TextAlign.Start;p.textDirection=p.textDirection||g.TextDirection.LTR;p.textHeightBehavior=p.textHeightBehavior||g.TextHeightBehavior.All;p.textStyle=g.TextStyle(p.textStyle);return p};g.TextStyle=function(p){p.color||(p.color=g.BLACK);p.decoration=p.decoration||0;p.decorationThickness=
p.decorationThickness||0;p.decorationStyle=p.decorationStyle||g.DecorationStyle.Solid;p.textBaseline=p.textBaseline||g.TextBaseline.Alphabetic;null==p.fontSize&&(p.fontSize=-1);p.letterSpacing=p.letterSpacing||0;p.wordSpacing=p.wordSpacing||0;null==p.heightMultiplier&&(p.heightMultiplier=-1);p.halfLeading=p.halfLeading||!1;p.fontStyle=h(p.fontStyle);return p};var F={},K=g._malloc(16),H=g._malloc(16),S=g._malloc(16);g.ParagraphBuilder.Make=function(p,A){w(p.textStyle);A=g.ParagraphBuilder._Make(p,
A);z(p.textStyle);return A};g.ParagraphBuilder.MakeFromFontProvider=function(p,A){w(p.textStyle);A=g.ParagraphBuilder._MakeFromFontProvider(p,A);z(p.textStyle);return A};g.ParagraphBuilder.MakeFromFontCollection=function(p,A){w(p.textStyle);A=g.ParagraphBuilder._MakeFromFontCollection(p,A);z(p.textStyle);return A};g.ParagraphBuilder.ShapeText=function(p,A,L){let V=0;for(const za of A)V+=za.length;if(V!==p.length)throw"Accumulated block lengths must equal text.length";return g.ParagraphBuilder._ShapeText(p,
A,L)};g.ParagraphBuilder.prototype.pushStyle=function(p){w(p);this._pushStyle(p);z(p)};g.ParagraphBuilder.prototype.pushPaintStyle=function(p,A,L){w(p);this._pushPaintStyle(p,A,L);z(p)};g.ParagraphBuilder.prototype.addPlaceholder=function(p,A,L,V,za){L=L||g.PlaceholderAlignment.Baseline;V=V||g.TextBaseline.Alphabetic;this._addPlaceholder(p||0,A||0,L,V,za||0)};g.ParagraphBuilder.prototype.setWordsUtf8=function(p){var A=l(p,"HEAPU32");this._setWordsUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setWordsUtf16=
function(p){var A=l(p,"HEAPU32");this._setWordsUtf16(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=function(p){var A=l(p,"HEAPU32");this._setGraphemeBreaksUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=function(p){var A=l(p,"HEAPU32");this._setGraphemeBreaksUtf16(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf8=function(p){var A=l(p,"HEAPU32");this._setLineBreaksUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf16=
function(p){var A=l(p,"HEAPU32");this._setLineBreaksUtf16(A,p&&p.length||0);k(A,p)}})})(r);a.Sd=a.Sd||[];a.Sd.push(function(){a.Path.prototype.op=function(g,d){return this._op(g,d)?this:null};a.Path.prototype.simplify=function(){return this._simplify()?this:null}});a.Sd=a.Sd||[];a.Sd.push(function(){a.Canvas.prototype.drawText=function(g,d,h,n,u){var w=la(g),z=a._malloc(w+1);ma(g,B,z,w+1);this._drawSimpleText(z,w,d,h,u,n);a._free(z)};a.Canvas.prototype.drawGlyphs=function(g,d,h,n,u,w){if(!(2*g.length<=
d.length))throw"Not enough positions for the array of gyphs";a.Pd(this.Od);const z=l(g,"HEAPU16"),F=l(d,"HEAPF32");this._drawGlyphs(g.length,z,F,h,n,u,w);k(F,d);k(z,g)};a.Font.prototype.getGlyphBounds=function(g,d,h){var n=l(g,"HEAPU16"),u=a._malloc(16*g.length);this._getGlyphWidthBounds(n,g.length,M,u,d||null);d=new Float32Array(a.HEAPU8.buffer,u,4*g.length);k(n,g);if(h)return h.set(d),a._free(u),h;g=Float32Array.from(d);a._free(u);return g};a.Font.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);
var n=la(g)+1,u=a._malloc(n);ma(g,B,u,n);g=a._malloc(2*d);d=this._getGlyphIDs(u,n-1,d,g);a._free(u);if(0>d)return a._free(g),null;u=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(u),a._free(g),h;h=Uint16Array.from(u);a._free(g);return h};a.Font.prototype.getGlyphIntercepts=function(g,d,h,n){var u=l(g,"HEAPU16"),w=l(d,"HEAPF32");return this._getGlyphIntercepts(u,g.length,!(g&&g._ck),w,d.length,!(d&&d._ck),h,n)};a.Font.prototype.getGlyphWidths=function(g,d,h){var n=l(g,"HEAPU16"),u=a._malloc(4*
g.length);this._getGlyphWidthBounds(n,g.length,u,M,d||null);d=new Float32Array(a.HEAPU8.buffer,u,g.length);k(n,g);if(h)return h.set(d),a._free(u),h;g=Float32Array.from(d);a._free(u);return g};a.FontMgr.FromData=function(){if(!arguments.length)return null;var g=arguments;1===g.length&&Array.isArray(g[0])&&(g=arguments[0]);if(!g.length)return null;for(var d=[],h=[],n=0;n<g.length;n++){var u=new Uint8Array(g[n]),w=l(u,"HEAPU8");d.push(w);h.push(u.byteLength)}d=l(d,"HEAPU32");h=l(h,"HEAPU32");g=a.FontMgr._fromData(d,
h,g.length);a._free(d);a._free(h);return g};a.Typeface.MakeFreeTypeFaceFromData=function(g){g=new Uint8Array(g);var d=l(g,"HEAPU8");return(g=a.Typeface._MakeFreeTypeFaceFromData(d,g.byteLength))?g:null};a.Typeface.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var n=la(g)+1,u=a._malloc(n);ma(g,B,u,n);g=a._malloc(2*d);d=this._getGlyphIDs(u,n-1,d,g);a._free(u);if(0>d)return a._free(g),null;u=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(u),a._free(g),h;h=Uint16Array.from(u);a._free(g);
return h};a.TextBlob.MakeOnPath=function(g,d,h,n){if(g&&g.length&&d&&d.countPoints()){if(1===d.countPoints())return this.MakeFromText(g,h);n||(n=0);var u=h.getGlyphIDs(g);u=h.getGlyphWidths(u);var w=[];d=new a.ContourMeasureIter(d,!1,1);for(var z=d.next(),F=new Float32Array(4),K=0;K<g.length&&z;K++){var H=u[K];n+=H/2;if(n>z.length()){z.delete();z=d.next();if(!z){g=g.substring(0,K);break}n=H/2}z.getPosTan(n,F);var S=F[2],p=F[3];w.push(S,p,F[0]-H/2*S,F[1]-H/2*p);n+=H/2}g=this.MakeFromRSXform(g,w,h);
z&&z.delete();d.delete();return g}};a.TextBlob.MakeFromRSXform=function(g,d,h){var n=la(g)+1,u=a._malloc(n);ma(g,B,u,n);g=l(d,"HEAPF32");h=a.TextBlob._MakeFromRSXform(u,n-1,g,h);a._free(u);return h?h:null};a.TextBlob.MakeFromRSXformGlyphs=function(g,d,h){var n=l(g,"HEAPU16");d=l(d,"HEAPF32");h=a.TextBlob._MakeFromRSXformGlyphs(n,2*g.length,d,h);k(n,g);return h?h:null};a.TextBlob.MakeFromGlyphs=function(g,d){var h=l(g,"HEAPU16");d=a.TextBlob._MakeFromGlyphs(h,2*g.length,d);k(h,g);return d?d:null};
a.TextBlob.MakeFromText=function(g,d){var h=la(g)+1,n=a._malloc(h);ma(g,B,n,h);g=a.TextBlob._MakeFromText(n,h-1,d);a._free(n);return g?g:null};a.MallocGlyphIDs=function(g){return a.Malloc(Uint16Array,g)}});a.Sd=a.Sd||[];a.Sd.push(function(){a.MakePicture=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._MakePicture(d,g.byteLength))?g:null}});a.Sd=a.Sd||[];a.Sd.push(function(){a.RuntimeEffect.Make=function(g,d){return a.RuntimeEffect._Make(g,{onError:d||function(h){console.log("RuntimeEffect error",
h)}})};a.RuntimeEffect.prototype.makeShader=function(g,d){var h=!g._ck,n=l(g,"HEAPF32");d=q(d);return this._makeShader(n,4*g.length,h,d)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(g,d,h){var n=!g._ck,u=l(g,"HEAPF32");h=q(h);for(var w=[],z=0;z<d.length;z++)w.push(d[z].Nd.Qd);d=l(w,"HEAPU32");return this._makeShaderWithChildren(u,4*g.length,n,d,w.length,h)}})})(r);
var na=aa({},r),oa="./this.program",qa="object"===typeof window,ra="function"===typeof importScripts,sa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,ta="",wa,xa,ya,fs,Ba,Ca;
if(sa)ta=ra?require("path").dirname(ta)+"/":__dirname+"/",Ca=()=>{Ba||(fs=require("fs"),Ba=require("path"))},wa=function(a,b){Ca();a=Ba.normalize(a);return fs.readFileSync(a,b?null:"utf8")},ya=a=>{a=wa(a,!0);a.buffer||(a=new Uint8Array(a));return a},xa=(a,b,c)=>{Ca();a=Ba.normalize(a);fs.readFile(a,function(e,f){e?c(e):b(f.buffer)})},1<process.argv.length&&(oa=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("unhandledRejection",function(a){throw a;}),r.inspect=function(){return"[Emscripten Module object]"};
else if(qa||ra)ra?ta=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),0!==ta.indexOf("blob:")?ta=ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1):ta="",wa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ra&&(ya=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),xa=(a,b,c)=>{var e=new XMLHttpRequest;
e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var Da=r.print||console.log.bind(console),Ea=r.printErr||console.warn.bind(console);aa(r,na);na=null;r.thisProgram&&(oa=r.thisProgram);var Fa=0,Ga;r.wasmBinary&&(Ga=r.wasmBinary);var noExitRuntime=r.noExitRuntime||!0;"object"!==typeof WebAssembly&&Ha("no native wasm support detected");
var Ia,Ja=!1,Ka="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function La(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&Ka)return Ka.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|l:(f&7)<<18|k<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function Na(a,b){return a?La(B,a,b):""}
function ma(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var m=a.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function la(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}var Oa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function Pa(a,b){var c=a>>1;for(var e=c+b/2;!(c>=e)&&Qa[c];)++c;c<<=1;if(32<c-a&&Oa)return Oa.decode(B.subarray(a,c));c="";for(e=0;!(e>=b/2);++e){var f=Sa[a+2*e>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}
function Ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Sa[b>>1]=a.charCodeAt(f),b+=2;Sa[b>>1]=0;return b-e}function Ua(a){return 2*a.length}function Va(a,b){for(var c=0,e="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}
function Wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}G[b>>2]=k;b+=4;if(b+4>c)break}G[b>>2]=0;return b-e}function Xa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var Ya,Za,B,Sa,Qa,G,$a,J,ab;
function bb(){var a=Ia.buffer;Ya=a;r.HEAP8=Za=new Int8Array(a);r.HEAP16=Sa=new Int16Array(a);r.HEAP32=G=new Int32Array(a);r.HEAPU8=B=new Uint8Array(a);r.HEAPU16=Qa=new Uint16Array(a);r.HEAPU32=$a=new Uint32Array(a);r.HEAPF32=J=new Float32Array(a);r.HEAPF64=ab=new Float64Array(a)}var cb,db=[],eb=[],fb=[];function hb(){var a=r.preRun.shift();db.unshift(a)}var ib=0,jb=null,kb=null;r.preloadedImages={};r.preloadedAudios={};
function Ha(a){if(r.onAbort)r.onAbort(a);a="Aborted("+a+")";Ea(a);Ja=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ea(a);throw a;}function lb(){return mb.startsWith("data:application/octet-stream;base64,")}var mb;mb="canvaskit.wasm";if(!lb()){var nb=mb;mb=r.locateFile?r.locateFile(nb,ta):ta+nb}function ob(){var a=mb;try{if(a==mb&&Ga)return new Uint8Array(Ga);if(ya)return ya(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ha(b)}}
function pb(){if(!Ga&&(qa||ra)){if("function"===typeof fetch&&!mb.startsWith("file://"))return fetch(mb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+mb+"'";return a.arrayBuffer()}).catch(function(){return ob()});if(xa)return new Promise(function(a,b){xa(mb,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ob()})}
function qb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(r);else{var c=b.Kf;"number"===typeof c?void 0===b.Be?N(c)():N(c)(b.Be):c(void 0===b.Be?null:b.Be)}}}function N(a){return cb.get(a)}
function rb(a){this.Qd=a-16;this.Af=function(b){G[this.Qd+4>>2]=b};this.xf=function(b){G[this.Qd+8>>2]=b};this.yf=function(){G[this.Qd>>2]=0};this.wf=function(){Za[this.Qd+12>>0]=0};this.zf=function(){Za[this.Qd+13>>0]=0};this.nf=function(b,c){this.Af(b);this.xf(c);this.yf();this.wf();this.zf()}}var sb=0,tb={},ub=[null,[],[]],vb={},wb={};function xb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function yb(a){return this.fromWireType($a[a>>2])}var zb={},Ab={},Bb={};
function Cb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Db(a,b){a=Cb(a);return function(){null;return b.apply(this,arguments)}}
function Eb(a){var b=Error,c=Db(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Fb=void 0;function Mb(a){throw new Fb(a);}
function Nb(a,b,c){function e(m){m=c(m);m.length!==a.length&&Mb("Mismatched type converter count");for(var q=0;q<a.length;++q)Ob(a[q],m[q])}a.forEach(function(m){Bb[m]=b});var f=Array(b.length),k=[],l=0;b.forEach(function(m,q){Ab.hasOwnProperty(m)?f[q]=Ab[m]:(k.push(m),zb.hasOwnProperty(m)||(zb[m]=[]),zb[m].push(function(){f[q]=Ab[m];++l;l===k.length&&e(f)}))});0===k.length&&e(f)}
function Pb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Qb=void 0;function O(a){for(var b="";B[a];)b+=Qb[B[a++]];return b}var Rb=void 0;function P(a){throw new Rb(a);}
function Ob(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||P('type "'+e+'" must have a positive integer typeid pointer');if(Ab.hasOwnProperty(a)){if(c.mf)return;P("Cannot register type '"+e+"' twice")}Ab[a]=b;delete Bb[a];zb.hasOwnProperty(a)&&(b=zb[a],delete zb[a],b.forEach(function(f){f()}))}function Sb(a){P(a.Nd.Td.Rd.name+" instance already deleted")}var Tb=!1;function Ub(){}
function Vb(a){--a.count.value;0===a.count.value&&(a.Vd?a.Zd.be(a.Vd):a.Td.Rd.be(a.Qd))}function Wb(a){if("undefined"===typeof FinalizationGroup)return Wb=b=>b,a;Tb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Qd?Vb(c):console.warn("object already deleted: "+c.Qd)});Wb=b=>{Tb.register(b,b.Nd,b.Nd);return b};Ub=b=>{Tb.unregister(b.Nd)};return Wb(a)}var Xb=void 0,Yb=[];function Zb(){for(;Yb.length;){var a=Yb.pop();a.Nd.ge=!1;a["delete"]()}}function $b(){}
var ac={};function bc(a,b,c){if(void 0===a[b].Ud){var e=a[b];a[b]=function(){a[b].Ud.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ud+")!");return a[b].Ud[arguments.length].apply(this,arguments)};a[b].Ud=[];a[b].Ud[e.ee]=e}}
function cc(a,b,c){r.hasOwnProperty(a)?((void 0===c||void 0!==r[a].Ud&&void 0!==r[a].Ud[c])&&P("Cannot register public name '"+a+"' twice"),bc(r,a,a),r.hasOwnProperty(c)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),r[a].Ud[c]=b):(r[a]=b,void 0!==c&&(r[a].Mf=c))}function dc(a,b,c,e,f,k,l,m){this.name=a;this.constructor=b;this.he=c;this.be=e;this.ae=f;this.ef=k;this.pe=l;this.bf=m;this.uf=[]}
function ec(a,b,c){for(;b!==c;)b.pe||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.pe(a),b=b.ae;return a}function fc(a,b){if(null===b)return this.Ee&&P("null is not a valid "+this.name),0;b.Nd||P('Cannot pass "'+gc(b)+'" as a '+this.name);b.Nd.Qd||P("Cannot pass deleted object as a pointer of type "+this.name);return ec(b.Nd.Qd,b.Nd.Td.Rd,this.Rd)}
function hc(a,b){if(null===b){this.Ee&&P("null is not a valid "+this.name);if(this.te){var c=this.Fe();null!==a&&a.push(this.be,c);return c}return 0}b.Nd||P('Cannot pass "'+gc(b)+'" as a '+this.name);b.Nd.Qd||P("Cannot pass deleted object as a pointer of type "+this.name);!this.se&&b.Nd.Td.se&&P("Cannot convert argument of type "+(b.Nd.Zd?b.Nd.Zd.name:b.Nd.Td.name)+" to parameter type "+this.name);c=ec(b.Nd.Qd,b.Nd.Td.Rd,this.Rd);if(this.te)switch(void 0===b.Nd.Vd&&P("Passing raw pointer to smart pointer is illegal"),
this.Ef){case 0:b.Nd.Zd===this?c=b.Nd.Vd:P("Cannot convert argument of type "+(b.Nd.Zd?b.Nd.Zd.name:b.Nd.Td.name)+" to parameter type "+this.name);break;case 1:c=b.Nd.Vd;break;case 2:if(b.Nd.Zd===this)c=b.Nd.Vd;else{var e=b.clone();c=this.vf(c,ic(function(){e["delete"]()}));null!==a&&a.push(this.be,c)}break;default:P("Unsupporting sharing policy")}return c}
function jc(a,b){if(null===b)return this.Ee&&P("null is not a valid "+this.name),0;b.Nd||P('Cannot pass "'+gc(b)+'" as a '+this.name);b.Nd.Qd||P("Cannot pass deleted object as a pointer of type "+this.name);b.Nd.Td.se&&P("Cannot convert argument of type "+b.Nd.Td.name+" to parameter type "+this.name);return ec(b.Nd.Qd,b.Nd.Td.Rd,this.Rd)}function kc(a,b,c){if(b===c)return a;if(void 0===c.ae)return null;a=kc(a,b,c.ae);return null===a?null:c.bf(a)}var lc={};
function mc(a,b){for(void 0===b&&P("ptr should not be undefined");a.ae;)b=a.pe(b),a=a.ae;return lc[b]}function uc(a,b){b.Td&&b.Qd||Mb("makeClassHandle requires ptr and ptrType");!!b.Zd!==!!b.Vd&&Mb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Wb(Object.create(a,{Nd:{value:b}}))}
function vc(a,b,c,e,f,k,l,m,q,x,y){this.name=a;this.Rd=b;this.Ee=c;this.se=e;this.te=f;this.tf=k;this.Ef=l;this.Oe=m;this.Fe=q;this.vf=x;this.be=y;f||void 0!==b.ae?this.toWireType=hc:(this.toWireType=e?fc:jc,this.Yd=null)}function wc(a,b,c){r.hasOwnProperty(a)||Mb("Replacing nonexistant public symbol");void 0!==r[a].Ud&&void 0!==c?r[a].Ud[c]=b:(r[a]=b,r[a].ee=c)}
function xc(a,b){var c=[];return function(){c.length=arguments.length;for(var e=0;e<arguments.length;e++)c[e]=arguments[e];a.includes("j")?(e=r["dynCall_"+a],e=c&&c.length?e.apply(null,[b].concat(c)):e.call(null,b)):e=N(b).apply(null,c);return e}}function yc(a,b){a=O(a);var c=a.includes("j")?xc(a,b):N(b);"function"!==typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var zc=void 0;function Ac(a){a=Bc(a);var b=O(a);Cc(a);return b}
function Dc(a,b){function c(k){f[k]||Ab[k]||(Bb[k]?Bb[k].forEach(c):(e.push(k),f[k]=!0))}var e=[],f={};b.forEach(c);throw new zc(a+": "+e.map(Ac).join([", "]));}
function Ec(a,b,c,e,f){var k=b.length;2>k&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Yd){m=!0;break}var q="void"!==b[0].name,x=k-2,y=Array(x),C=[],E=[];return function(){arguments.length!==x&&P("function "+a+" called with "+arguments.length+" arguments, expected "+x+" args!");E.length=0;C.length=l?2:1;C[0]=f;if(l){var v=b[1].toWireType(E,this);C[1]=v}for(var D=0;D<x;++D)y[D]=
b[D+2].toWireType(E,arguments[D]),C.push(y[D]);D=e.apply(null,C);if(m)xb(E);else for(var I=l?1:2;I<b.length;I++){var R=1===I?v:y[I-2];null!==b[I].Yd&&b[I].Yd(R)}v=q?b[0].fromWireType(D):void 0;return v}}function Fc(a,b){for(var c=[],e=0;e<a;e++)c.push(G[(b>>2)+e]);return c}var Gc=[],Hc=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ic(a){4<a&&0===--Hc[a].Ge&&(Hc[a]=void 0,Gc.push(a))}function Jc(a){a||P("Cannot use deleted val. handle = "+a);return Hc[a].value}
function ic(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Gc.length?Gc.pop():Hc.length;Hc[b]={Ge:1,value:a};return b}}function Kc(a,b,c){switch(b){case 0:return function(e){return this.fromWireType((c?Za:B)[e])};case 1:return function(e){return this.fromWireType((c?Sa:Qa)[e>>1])};case 2:return function(e){return this.fromWireType((c?G:$a)[e>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function Lc(a,b){var c=Ab[a];void 0===c&&P(b+" has unknown type "+Ac(a));return c}function gc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Mc(a,b){switch(b){case 2:return function(c){return this.fromWireType(J[c>>2])};case 3:return function(c){return this.fromWireType(ab[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Nc(a,b,c){switch(b){case 0:return c?function(e){return Za[e]}:function(e){return B[e]};case 1:return c?function(e){return Sa[e>>1]}:function(e){return Qa[e>>1]};case 2:return c?function(e){return G[e>>2]}:function(e){return $a[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Oc={};function Pc(a){var b=Oc[a];return void 0===b?O(a):b}var Qc=[];
function Rc(){function a(b){b.$$$embind_global$$$=b;var c="object"===typeof $$$embind_global$$$&&b.$$$embind_global$$$===b;c||delete b.$$$embind_global$$$;return c}if("object"===typeof globalThis)return globalThis;if("object"===typeof $$$embind_global$$$)return $$$embind_global$$$;"object"===typeof global&&a(global)?$$$embind_global$$$=global:"object"===typeof self&&a(self)&&($$$embind_global$$$=self);if("object"===typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function Sc(a){var b=Qc.length;Qc.push(a);return b}function Tc(a,b){for(var c=Array(a),e=0;e<a;++e)c[e]=Lc(G[(b>>2)+e],"parameter "+e);return c}var Uc=[];function Vc(a){var b=Array(a+1);return function(c,e,f){b[0]=c;for(var k=0;k<a;++k){var l=Lc(G[(e>>2)+k],"parameter "+k);b[k+1]=l.readValueFromPointer(f);f+=l.argPackAdvance}c=new (c.bind.apply(c,b));return ic(c)}}var Wc={},Xc;Xc=sa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function Yc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,k){b.drawArraysInstancedANGLE(c,e,f,k)},a.drawElementsInstanced=function(c,e,f,k,l){b.drawElementsInstancedANGLE(c,e,f,k,l)})}
function Zc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function $c(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
var ad=1,bd=[],cd=[],dd=[],ed=[],ha=[],fd=[],gd=[],ka=[],hd=[],jd=[],kd={},ld={},nd=4;function Q(a){od||(od=a)}function fa(a){for(var b=ad++,c=a.length;c<b;c++)a[c]=null;return b}function ia(a,b){a.Me||(a.Me=a.getContext,a.getContext=function(e,f){f=a.Me(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",b):a.getContext("webgl",b);return c?pd(c,b):0}
function pd(a,b){var c=fa(ka),e={lf:c,attributes:b,version:b.majorVersion,$d:a};a.canvas&&(a.canvas.Re=e);ka[c]=e;("undefined"===typeof b.cf||b.cf)&&qd(e);return c}function ja(a){t=ka[a];r.Jf=T=t&&t.$d;return!(a&&!T)}
function qd(a){a||(a=t);if(!a.pf){a.pf=!0;var b=a.$d;Yc(b);Zc(b);$c(b);b.Je=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ne=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ke=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ke)b.Ke=b.getExtension("EXT_disjoint_timer_query");b.Lf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var t,od,rd=[];function sd(a,b,c,e){for(var f=0;f<a;f++){var k=T[c](),l=k&&fa(e);k?(k.name=l,e[l]=k):Q(1282);G[b+4*f>>2]=l}}
function td(a,b,c){if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 34814:case 36345:e=0;break;case 34466:var f=T.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>t.version){Q(1282);return}e=2*(T.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>t.version){Q(1280);return}e=33307==a?3:0}if(void 0===e)switch(f=T.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":Q(1280);return;case "object":if(null===
f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=0;break;default:Q(1280);return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:G[b+4*a>>2]=f[a];break;case 2:J[b+4*a>>2]=f[a];break;case 4:Za[b+a>>0]=f[a]?1:0}return}try{e=f.name|0}catch(k){Q(1280);
Ea("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+k+")");return}}break;default:Q(1280);Ea("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(c){case 1:c=e;$a[b>>2]=c;$a[b+4>>2]=(c-$a[b>>2])/4294967296;break;case 0:G[b>>2]=e;break;case 2:J[b>>2]=e;break;case 4:Za[b>>0]=e?1:0}}else Q(1281)}function ud(a){var b=la(a)+1,c=vd(b);ma(a,B,c,b);return c}
function wd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function xd(a){a-=5120;return 0==a?Za:1==a?B:2==a?Sa:4==a?G:6==a?J:5==a||28922==a||28520==a||30779==a||30782==a?$a:Qa}function yd(a,b,c,e,f){a=xd(a);var k=31-Math.clz32(a.BYTES_PER_ELEMENT),l=nd;return a.subarray(f>>k,f+e*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+l-1&-l)>>k)}
function U(a){var b=T.Ze;if(b){var c=b.oe[a];"number"===typeof c&&(b.oe[a]=c=T.getUniformLocation(b,b.Pe[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}var zd=[],Ad=[],Bd={};
function Cd(){if(!Dd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:oa||"./this.program"},b;for(b in Bd)void 0===Bd[b]?delete a[b]:a[b]=Bd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Dd=c}return Dd}var Dd;function Ed(a){return 0===a%4&&(0!==a%100||0===a%400)}function Fd(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}
var Gd=[31,29,31,30,31,30,31,31,30,31,30,31],Hd=[31,28,31,30,31,30,31,31,30,31,30,31];function Id(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Ed(a.getFullYear())?Gd:Hd)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Jd(a,b,c,e){function f(v,D,I){for(v="number"===typeof v?v.toString():v||"";v.length<D;)v=I[0]+v;return v}function k(v,D){return f(v,D,"0")}function l(v,D){function I(ca){return 0>ca?-1:0<ca?1:0}var R;0===(R=I(v.getFullYear()-D.getFullYear()))&&0===(R=I(v.getMonth()-D.getMonth()))&&(R=I(v.getDate()-D.getDate()));return R}function m(v){switch(v.getDay()){case 0:return new Date(v.getFullYear()-1,11,29);case 1:return v;case 2:return new Date(v.getFullYear(),0,3);case 3:return new Date(v.getFullYear(),
0,2);case 4:return new Date(v.getFullYear(),0,1);case 5:return new Date(v.getFullYear()-1,11,31);case 6:return new Date(v.getFullYear()-1,11,30)}}function q(v){v=Id(new Date(v.Wd+1900,0,1),v.ze);var D=new Date(v.getFullYear()+1,0,4),I=m(new Date(v.getFullYear(),0,4));D=m(D);return 0>=l(I,v)?0>=l(D,v)?v.getFullYear()+1:v.getFullYear():v.getFullYear()-1}var x=G[e+40>>2];e={Hf:G[e>>2],Gf:G[e+4>>2],xe:G[e+8>>2],ne:G[e+12>>2],ie:G[e+16>>2],Wd:G[e+20>>2],ye:G[e+24>>2],ze:G[e+28>>2],Pf:G[e+32>>2],Ff:G[e+
36>>2],If:x?Na(x):""};c=Na(c);x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in x)c=c.replace(new RegExp(y,"g"),x[y]);var C="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");x={"%a":function(v){return C[v.ye].substring(0,3)},"%A":function(v){return C[v.ye]},"%b":function(v){return E[v.ie].substring(0,3)},"%B":function(v){return E[v.ie]},"%C":function(v){return k((v.Wd+1900)/100|0,2)},"%d":function(v){return k(v.ne,2)},"%e":function(v){return f(v.ne,2," ")},"%g":function(v){return q(v).toString().substring(2)},"%G":function(v){return q(v)},"%H":function(v){return k(v.xe,
2)},"%I":function(v){v=v.xe;0==v?v=12:12<v&&(v-=12);return k(v,2)},"%j":function(v){return k(v.ne+Fd(Ed(v.Wd+1900)?Gd:Hd,v.ie-1),3)},"%m":function(v){return k(v.ie+1,2)},"%M":function(v){return k(v.Gf,2)},"%n":function(){return"\n"},"%p":function(v){return 0<=v.xe&&12>v.xe?"AM":"PM"},"%S":function(v){return k(v.Hf,2)},"%t":function(){return"\t"},"%u":function(v){return v.ye||7},"%U":function(v){var D=new Date(v.Wd+1900,0,1),I=0===D.getDay()?D:Id(D,7-D.getDay());v=new Date(v.Wd+1900,v.ie,v.ne);return 0>
l(I,v)?k(Math.ceil((31-I.getDate()+(Fd(Ed(v.getFullYear())?Gd:Hd,v.getMonth()-1)-31)+v.getDate())/7),2):0===l(I,D)?"01":"00"},"%V":function(v){var D=new Date(v.Wd+1901,0,4),I=m(new Date(v.Wd+1900,0,4));D=m(D);var R=Id(new Date(v.Wd+1900,0,1),v.ze);return 0>l(R,I)?"53":0>=l(D,R)?"01":k(Math.ceil((I.getFullYear()<v.Wd+1900?v.ze+32-I.getDate():v.ze+1-I.getDate())/7),2)},"%w":function(v){return v.ye},"%W":function(v){var D=new Date(v.Wd,0,1),I=1===D.getDay()?D:Id(D,0===D.getDay()?1:7-D.getDay()+1);v=
new Date(v.Wd+1900,v.ie,v.ne);return 0>l(I,v)?k(Math.ceil((31-I.getDate()+(Fd(Ed(v.getFullYear())?Gd:Hd,v.getMonth()-1)-31)+v.getDate())/7),2):0===l(I,D)?"01":"00"},"%y":function(v){return(v.Wd+1900).toString().substring(2)},"%Y":function(v){return v.Wd+1900},"%z":function(v){v=v.Ff;var D=0<=v;v=Math.abs(v)/60;return(D?"+":"-")+String("0000"+(v/60*100+v%60)).slice(-4)},"%Z":function(v){return v.If},"%%":function(){return"%"}};for(y in x)c.includes(y)&&(c=c.replace(new RegExp(y,"g"),x[y](e)));y=Kd(c);
if(y.length>b)return 0;Za.set(y,a);return y.length-1}Fb=r.InternalError=Eb("InternalError");for(var Ld=Array(256),Md=0;256>Md;++Md)Ld[Md]=String.fromCharCode(Md);Qb=Ld;Rb=r.BindingError=Eb("BindingError");$b.prototype.isAliasOf=function(a){if(!(this instanceof $b&&a instanceof $b))return!1;var b=this.Nd.Td.Rd,c=this.Nd.Qd,e=a.Nd.Td.Rd;for(a=a.Nd.Qd;b.ae;)c=b.pe(c),b=b.ae;for(;e.ae;)a=e.pe(a),e=e.ae;return b===e&&c===a};
$b.prototype.clone=function(){this.Nd.Qd||Sb(this);if(this.Nd.me)return this.Nd.count.value+=1,this;var a=Wb,b=Object,c=b.create,e=Object.getPrototypeOf(this),f=this.Nd;a=a(c.call(b,e,{Nd:{value:{count:f.count,ge:f.ge,me:f.me,Qd:f.Qd,Td:f.Td,Vd:f.Vd,Zd:f.Zd}}}));a.Nd.count.value+=1;a.Nd.ge=!1;return a};$b.prototype["delete"]=function(){this.Nd.Qd||Sb(this);this.Nd.ge&&!this.Nd.me&&P("Object already scheduled for deletion");Ub(this);Vb(this.Nd);this.Nd.me||(this.Nd.Vd=void 0,this.Nd.Qd=void 0)};
$b.prototype.isDeleted=function(){return!this.Nd.Qd};$b.prototype.deleteLater=function(){this.Nd.Qd||Sb(this);this.Nd.ge&&!this.Nd.me&&P("Object already scheduled for deletion");Yb.push(this);1===Yb.length&&Xb&&Xb(Zb);this.Nd.ge=!0;return this};vc.prototype.ff=function(a){this.Oe&&(a=this.Oe(a));return a};vc.prototype.Ie=function(a){this.be&&this.be(a)};vc.prototype.argPackAdvance=8;vc.prototype.readValueFromPointer=yb;vc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
vc.prototype.fromWireType=function(a){function b(){return this.te?uc(this.Rd.he,{Td:this.tf,Qd:c,Zd:this,Vd:a}):uc(this.Rd.he,{Td:this,Qd:a})}var c=this.ff(a);if(!c)return this.Ie(a),null;var e=mc(this.Rd,c);if(void 0!==e){if(0===e.Nd.count.value)return e.Nd.Qd=c,e.Nd.Vd=a,e.clone();e=e.clone();this.Ie(a);return e}e=this.Rd.ef(c);e=ac[e];if(!e)return b.call(this);e=this.se?e.Ye:e.pointerType;var f=kc(c,this.Rd,e.Rd);return null===f?b.call(this):this.te?uc(e.Rd.he,{Td:e,Qd:f,Zd:this,Vd:a}):uc(e.Rd.he,
{Td:e,Qd:f})};r.getInheritedInstanceCount=function(){return Object.keys(lc).length};r.getLiveInheritedInstances=function(){var a=[],b;for(b in lc)lc.hasOwnProperty(b)&&a.push(lc[b]);return a};r.flushPendingDeletes=Zb;r.setDelayFunction=function(a){Xb=a;Yb.length&&Xb&&Xb(Zb)};zc=r.UnboundTypeError=Eb("UnboundTypeError");r.count_emval_handles=function(){for(var a=0,b=5;b<Hc.length;++b)void 0!==Hc[b]&&++a;return a};
r.get_first_emval=function(){for(var a=5;a<Hc.length;++a)if(void 0!==Hc[a])return Hc[a];return null};for(var T,Nd=0;32>Nd;++Nd)rd.push(Array(Nd));var Od=new Float32Array(288);for(Nd=0;288>Nd;++Nd)zd[Nd]=Od.subarray(0,Nd+1);var Pd=new Int32Array(288);for(Nd=0;288>Nd;++Nd)Ad[Nd]=Pd.subarray(0,Nd+1);function Kd(a){var b=Array(la(a)+1);ma(a,b,0,b.length);return b}
var he={K:function(a){return vd(a+16)+16},J:function(a,b,c){(new rb(a)).nf(b,c);sb++;throw a;},aa:function(){return 0},Fb:function(){},Cb:function(){},Ib:function(){return 0},Db:function(){},zb:function(a,b,c,e,f,k){k<<=12;if(0!==(e&16)&&0!==a%65536)b=-28;else if(0!==(e&32)){a=65536*Math.ceil(b/65536);var l=Qd(65536,a);l?(B.fill(0,l,l+a),a=l):a=0;a?(tb[a]={sf:a,rf:b,Xe:!0,fd:f,Nf:c,flags:e,offset:k},b=a):b=-48}else b=-52;return b},yb:function(a,b){var c=tb[a];0!==b&&c?(b===c.rf&&(tb[a]=null,c.Xe&&
Cc(c.sf)),a=0):a=-28;return a},ba:function(){},Eb:function(){},C:function(a){var b=wb[a];delete wb[a];var c=b.Fe,e=b.be,f=b.Le,k=f.map(function(l){return l.kf}).concat(f.map(function(l){return l.Cf}));Nb([a],k,function(l){var m={};f.forEach(function(q,x){var y=l[x],C=q.hf,E=q.jf,v=l[x+f.length],D=q.Bf,I=q.Df;m[q.df]={read:function(R){return y.fromWireType(C(E,R))},write:function(R,ca){var da=[];D(I,R,v.toWireType(da,ca));xb(da)}}});return[{name:b.name,fromWireType:function(q){var x={},y;for(y in m)x[y]=
m[y].read(q);e(q);return x},toWireType:function(q,x){for(var y in m)if(!(y in x))throw new TypeError('Missing field:  "'+y+'"');var C=c();for(y in m)m[y].write(C,x[y]);null!==q&&q.push(e,C);return C},argPackAdvance:8,readValueFromPointer:yb,Yd:e}]})},sb:function(){},Kb:function(a,b,c,e,f){var k=Pb(c);b=O(b);Ob(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,m){return m?e:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var m=Za;else if(2===c)m=Sa;else if(4===c)m=G;
else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[l>>k])},Yd:null})},r:function(a,b,c,e,f,k,l,m,q,x,y,C,E){y=O(y);k=yc(f,k);m&&(m=yc(l,m));x&&(x=yc(q,x));E=yc(C,E);var v=Cb(y);cc(v,function(){Dc("Cannot construct "+y+" due to unbound types",[e])});Nb([a,b,c],e?[e]:[],function(D){D=D[0];if(e){var I=D.Rd;var R=I.he}else R=$b.prototype;D=Db(v,function(){if(Object.getPrototypeOf(this)!==ca)throw new Rb("Use 'new' to construct "+y);if(void 0===da.ce)throw new Rb(y+" has no accessible constructor");
var Ma=da.ce[arguments.length];if(void 0===Ma)throw new Rb("Tried to invoke ctor of "+y+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(da.ce).toString()+") parameters instead!");return Ma.apply(this,arguments)});var ca=Object.create(R,{constructor:{value:D}});D.prototype=ca;var da=new dc(y,D,ca,E,I,k,m,x);I=new vc(y,da,!0,!1,!1);R=new vc(y+"*",da,!1,!1,!1);var ua=new vc(y+" const*",da,!1,!0,!1);ac[a]={pointerType:R,Ye:ua};wc(v,D);return[I,R,ua]})},i:function(a,
b,c,e,f,k,l){var m=Fc(c,e);b=O(b);k=yc(f,k);Nb([],[a],function(q){function x(){Dc("Cannot call "+y+" due to unbound types",m)}q=q[0];var y=q.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var C=q.Rd.constructor;void 0===C[b]?(x.ee=c-1,C[b]=x):(bc(C,b,y),C[b].Ud[c-1]=x);Nb([],m,function(E){E=[E[0],null].concat(E.slice(1));E=Ec(y,E,null,k,l);void 0===C[b].Ud?(E.ee=c-1,C[b]=E):C[b].Ud[c-1]=E;return[]});return[]})},A:function(a,b,c,e,f,k){0<b||Ha(void 0);var l=Fc(b,c);f=yc(e,f);Nb([],[a],function(m){m=
m[0];var q="constructor "+m.name;void 0===m.Rd.ce&&(m.Rd.ce=[]);if(void 0!==m.Rd.ce[b-1])throw new Rb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.Rd.ce[b-1]=()=>{Dc("Cannot construct "+m.name+" due to unbound types",l)};Nb([],l,function(x){x.splice(1,0,null);m.Rd.ce[b-1]=Ec(q,x,null,f,k);return[]});return[]})},d:function(a,b,c,e,f,
k,l,m){var q=Fc(c,e);b=O(b);k=yc(f,k);Nb([],[a],function(x){function y(){Dc("Cannot call "+C+" due to unbound types",q)}x=x[0];var C=x.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);m&&x.Rd.uf.push(b);var E=x.Rd.he,v=E[b];void 0===v||void 0===v.Ud&&v.className!==x.name&&v.ee===c-2?(y.ee=c-2,y.className=x.name,E[b]=y):(bc(E,b,C),E[b].Ud[c-2]=y);Nb([],q,function(D){D=Ec(C,D,x,k,l);void 0===E[b].Ud?(D.ee=c-2,E[b]=D):E[b].Ud[c-2]=D;return[]});return[]})},v:function(a,b,c){a=O(a);Nb([],[b],
function(e){e=e[0];r[a]=e.fromWireType(c);return[]})},Jb:function(a,b){b=O(b);Ob(a,{name:b,fromWireType:function(c){var e=Jc(c);Ic(c);return e},toWireType:function(c,e){return ic(e)},argPackAdvance:8,readValueFromPointer:yb,Yd:null})},q:function(a,b,c,e){function f(){}c=Pb(c);b=O(b);f.values={};Ob(a,{name:b,constructor:f,fromWireType:function(k){return this.constructor.values[k]},toWireType:function(k,l){return l.value},argPackAdvance:8,readValueFromPointer:Kc(b,c,e),Yd:null});cc(b,f)},f:function(a,
b,c){var e=Lc(a,"enum");b=O(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:Db(e.name+"_"+b,function(){})}});a.values[c]=e;a[b]=e},ca:function(a,b,c){c=Pb(c);b=O(b);Ob(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){return f},argPackAdvance:8,readValueFromPointer:Mc(b,c),Yd:null})},y:function(a,b,c,e,f,k){var l=Fc(b,c);a=O(a);f=yc(e,f);cc(a,function(){Dc("Cannot call "+a+" due to unbound types",l)},b-1);Nb([],l,function(m){m=[m[0],
null].concat(m.slice(1));wc(a,Ec(a,m,null,f,k),b-1);return[]})},E:function(a,b,c,e,f){b=O(b);-1===f&&(f=4294967295);f=Pb(c);var k=m=>m;if(0===e){var l=32-8*c;k=m=>m<<l>>>l}c=b.includes("unsigned")?function(m,q){return q>>>0}:function(m,q){return q};Ob(a,{name:b,fromWireType:k,toWireType:c,argPackAdvance:8,readValueFromPointer:Nc(b,f,0!==e),Yd:null})},w:function(a,b,c){function e(k){k>>=2;var l=$a;return new f(Ya,l[k+1],l[k])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,
Float32Array,Float64Array][b];c=O(c);Ob(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{mf:!0})},u:function(a,b,c,e,f,k,l,m,q,x,y,C){c=O(c);k=yc(f,k);m=yc(l,m);x=yc(q,x);C=yc(y,C);Nb([a],[b],function(E){E=E[0];return[new vc(c,E.Rd,!1,!1,!0,E,e,k,m,x,C)]})},da:function(a,b){b=O(b);var c="std::string"===b;Ob(a,{name:b,fromWireType:function(e){var f=$a[e>>2];if(c)for(var k=e+4,l=0;l<=f;++l){var m=e+4+l;if(l==f||0==B[m]){k=Na(k,m-k);if(void 0===q)var q=k;else q+=String.fromCharCode(0),
q+=k;k=m+1}}else{q=Array(f);for(l=0;l<f;++l)q[l]=String.fromCharCode(B[e+4+l]);q=q.join("")}Cc(e);return q},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var k="string"===typeof f;k||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||P("Cannot pass non-string to std::string");var l=(c&&k?()=>la(f):()=>f.length)(),m=vd(4+l+1);$a[m>>2]=l;if(c&&k)ma(f,B,m+4,l+1);else if(k)for(k=0;k<l;++k){var q=f.charCodeAt(k);255<q&&(Cc(m),P("String has UTF-16 code units that do not fit in 8 bits"));
B[m+4+k]=q}else for(k=0;k<l;++k)B[m+4+k]=f[k];null!==e&&e.push(Cc,m);return m},argPackAdvance:8,readValueFromPointer:yb,Yd:function(e){Cc(e)}})},U:function(a,b,c){c=O(c);if(2===b){var e=Pa;var f=Ta;var k=Ua;var l=()=>Qa;var m=1}else 4===b&&(e=Va,f=Wa,k=Xa,l=()=>$a,m=2);Ob(a,{name:c,fromWireType:function(q){for(var x=$a[q>>2],y=l(),C,E=q+4,v=0;v<=x;++v){var D=q+4+v*b;if(v==x||0==y[D>>m])E=e(E,D-E),void 0===C?C=E:(C+=String.fromCharCode(0),C+=E),E=D+b}Cc(q);return C},toWireType:function(q,x){"string"!==
typeof x&&P("Cannot pass non-string to C++ string type "+c);var y=k(x),C=vd(4+y+b);$a[C>>2]=y>>m;f(x,C+4,y+b);null!==q&&q.push(Cc,C);return C},argPackAdvance:8,readValueFromPointer:yb,Yd:function(q){Cc(q)}})},D:function(a,b,c,e,f,k){wb[a]={name:O(b),Fe:yc(c,e),be:yc(f,k),Le:[]}},h:function(a,b,c,e,f,k,l,m,q,x){wb[a].Le.push({df:O(b),kf:c,hf:yc(e,f),jf:k,Cf:l,Bf:yc(m,q),Df:x})},Lb:function(a,b){b=O(b);Ob(a,{qf:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},vb:function(){throw"longjmp";
},M:function(a,b,c){a=Jc(a);b=Lc(b,"emval::as");var e=[],f=ic(e);G[c>>2]=f;return b.toWireType(e,a)},N:function(a,b,c,e,f){a=Qc[a];b=Jc(b);c=Pc(c);var k=[];G[e>>2]=ic(k);return a(b,c,k,f)},B:function(a,b,c,e){a=Qc[a];b=Jc(b);c=Pc(c);a(b,c,null,e)},g:Ic,W:function(a){if(0===a)return ic(Rc());a=Pc(a);return ic(Rc()[a])},z:function(a,b){var c=Tc(a,b),e=c[0];b=e.name+"_$"+c.slice(1).map(function(l){return l.name}).join("_")+"$";var f=Uc[b];if(void 0!==f)return f;var k=Array(a-1);f=Sc((l,m,q,x)=>{for(var y=
0,C=0;C<a-1;++C)k[C]=c[C+1].readValueFromPointer(x+y),y+=c[C+1].argPackAdvance;l=l[m].apply(l,k);for(C=0;C<a-1;++C)c[C+1].$e&&c[C+1].$e(k[C]);if(!e.qf)return e.toWireType(q,l)});return Uc[b]=f},L:function(a,b){a=Jc(a);b=Jc(b);return ic(a[b])},s:function(a){4<a&&(Hc[a].Ge+=1)},V:function(a,b,c,e){a=Jc(a);var f=Wc[b];f||(f=Vc(b),Wc[b]=f);return f(a,c,e)},Q:function(){return ic([])},k:function(a){return ic(Pc(a))},H:function(){return ic({})},ob:function(a){a=Jc(a);return!a},F:function(a){var b=Jc(a);
xb(b);Ic(a)},p:function(a,b,c){a=Jc(a);b=Jc(b);c=Jc(c);a[b]=c},l:function(a,b){a=Lc(a,"_emval_take_value");a=a.readValueFromPointer(b);return ic(a)},c:function(){Ha("")},xb:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Xc();else return G[Rd()>>2]=28,-1;G[b>>2]=a/1E3|0;G[b+4>>2]=a%1E3*1E6|0;return 0},kb:function(a){T.activeTexture(a)},jb:function(a,b){T.attachShader(cd[a],fd[b])},ib:function(a,b,c){T.bindAttribLocation(cd[a],b,Na(c))},hb:function(a,b){35051==a?T.Ce=b:35052==a&&(T.fe=b);
T.bindBuffer(a,bd[b])},fa:function(a,b){T.bindFramebuffer(a,dd[b])},lc:function(a,b){T.bindRenderbuffer(a,ed[b])},Vb:function(a,b){T.bindSampler(a,hd[b])},gb:function(a,b){T.bindTexture(a,ha[b])},Dc:function(a){T.bindVertexArray(gd[a])},Ac:function(a){T.bindVertexArray(gd[a])},fb:function(a,b,c,e){T.blendColor(a,b,c,e)},eb:function(a){T.blendEquation(a)},db:function(a,b){T.blendFunc(a,b)},$b:function(a,b,c,e,f,k,l,m,q,x){T.blitFramebuffer(a,b,c,e,f,k,l,m,q,x)},cb:function(a,b,c,e){2<=t.version?c?
T.bufferData(a,B,e,c,b):T.bufferData(a,b,e):T.bufferData(a,c?B.subarray(c,c+b):b,e)},bb:function(a,b,c,e){2<=t.version?T.bufferSubData(a,b,B,e,c):T.bufferSubData(a,b,B.subarray(e,e+c))},kc:function(a){return T.checkFramebufferStatus(a)},X:function(a){T.clear(a)},ea:function(a,b,c,e){T.clearColor(a,b,c,e)},$:function(a){T.clearStencil(a)},mb:function(a,b,c,e){return T.clientWaitSync(jd[a],b,(c>>>0)+4294967296*e)},ab:function(a,b,c,e){T.colorMask(!!a,!!b,!!c,!!e)},$a:function(a){T.compileShader(fd[a])},
_a:function(a,b,c,e,f,k,l,m){2<=t.version?T.fe?T.compressedTexImage2D(a,b,c,e,f,k,l,m):T.compressedTexImage2D(a,b,c,e,f,k,B,m,l):T.compressedTexImage2D(a,b,c,e,f,k,m?B.subarray(m,m+l):null)},Za:function(a,b,c,e,f,k,l,m,q){2<=t.version?T.fe?T.compressedTexSubImage2D(a,b,c,e,f,k,l,m,q):T.compressedTexSubImage2D(a,b,c,e,f,k,l,B,q,m):T.compressedTexSubImage2D(a,b,c,e,f,k,l,q?B.subarray(q,q+m):null)},Zb:function(a,b,c,e,f){T.copyBufferSubData(a,b,c,e,f)},Ya:function(a,b,c,e,f,k,l,m){T.copyTexSubImage2D(a,
b,c,e,f,k,l,m)},Xa:function(){var a=fa(cd),b=T.createProgram();b.name=a;b.we=b.ue=b.ve=0;b.He=1;cd[a]=b;return a},Wa:function(a){var b=fa(fd);fd[b]=T.createShader(a);return b},Va:function(a){T.cullFace(a)},Ua:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=bd[e];f&&(T.deleteBuffer(f),f.name=0,bd[e]=null,e==T.Ce&&(T.Ce=0),e==T.fe&&(T.fe=0))}},jc:function(a,b){for(var c=0;c<a;++c){var e=G[b+4*c>>2],f=dd[e];f&&(T.deleteFramebuffer(f),f.name=0,dd[e]=null)}},Ta:function(a){if(a){var b=cd[a];b?(T.deleteProgram(b),
b.name=0,cd[a]=null):Q(1281)}},ic:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=ed[e];f&&(T.deleteRenderbuffer(f),f.name=0,ed[e]=null)}},Ub:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=hd[e];f&&(T.deleteSampler(f),f.name=0,hd[e]=null)}},Sa:function(a){if(a){var b=fd[a];b?(T.deleteShader(b),fd[a]=null):Q(1281)}},Yb:function(a){if(a){var b=jd[a];b?(T.deleteSync(b),b.name=0,jd[a]=null):Q(1281)}},Ra:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=ha[e];f&&(T.deleteTexture(f),
f.name=0,ha[e]=null)}},Cc:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2];T.deleteVertexArray(gd[e]);gd[e]=null}},zc:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2];T.deleteVertexArray(gd[e]);gd[e]=null}},Qa:function(a){T.depthMask(!!a)},Pa:function(a){T.disable(a)},Oa:function(a){T.disableVertexAttribArray(a)},Na:function(a,b,c){T.drawArrays(a,b,c)},xc:function(a,b,c,e){T.drawArraysInstanced(a,b,c,e)},vc:function(a,b,c,e,f){T.Je.drawArraysInstancedBaseInstanceWEBGL(a,b,c,e,f)},tc:function(a,
b){for(var c=rd[a],e=0;e<a;e++)c[e]=G[b+4*e>>2];T.drawBuffers(c)},Ma:function(a,b,c,e){T.drawElements(a,b,c,e)},wc:function(a,b,c,e,f){T.drawElementsInstanced(a,b,c,e,f)},uc:function(a,b,c,e,f,k,l){T.Je.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,e,f,k,l)},pc:function(a,b,c,e,f,k){T.drawElements(a,e,f,k)},La:function(a){T.enable(a)},Ka:function(a){T.enableVertexAttribArray(a)},Xb:function(a,b){return(a=T.fenceSync(a,b))?(b=fa(jd),a.name=b,jd[b]=a,b):0},Ja:function(){T.finish()},Ia:function(){T.flush()},
hc:function(a,b,c,e){T.framebufferRenderbuffer(a,b,c,ed[e])},gc:function(a,b,c,e,f){T.framebufferTexture2D(a,b,c,ha[e],f)},Ha:function(a){T.frontFace(a)},Ga:function(a,b){sd(a,b,"createBuffer",bd)},fc:function(a,b){sd(a,b,"createFramebuffer",dd)},ec:function(a,b){sd(a,b,"createRenderbuffer",ed)},Tb:function(a,b){sd(a,b,"createSampler",hd)},Fa:function(a,b){sd(a,b,"createTexture",ha)},Bc:function(a,b){sd(a,b,"createVertexArray",gd)},yc:function(a,b){sd(a,b,"createVertexArray",gd)},dc:function(a){T.generateMipmap(a)},
Ea:function(a,b,c){c?G[c>>2]=T.getBufferParameter(a,b):Q(1281)},Da:function(){var a=T.getError()||od;od=0;return a},Ca:function(a,b){td(a,b,2)},cc:function(a,b,c,e){a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;G[e>>2]=a},O:function(a,b){td(a,b,0)},Ba:function(a,b,c,e){a=T.getProgramInfoLog(cd[a]);null===a&&(a="(unknown error)");b=0<b&&e?ma(a,B,e,b):0;c&&(G[c>>2]=b)},Aa:function(a,b,c){if(c)if(a>=ad)Q(1281);else if(a=cd[a],35716==
b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b){if(!a.we)for(b=0;b<T.getProgramParameter(a,35718);++b)a.we=Math.max(a.we,T.getActiveUniform(a,b).name.length+1);G[c>>2]=a.we}else if(35722==b){if(!a.ue)for(b=0;b<T.getProgramParameter(a,35721);++b)a.ue=Math.max(a.ue,T.getActiveAttrib(a,b).name.length+1);G[c>>2]=a.ue}else if(35381==b){if(!a.ve)for(b=0;b<T.getProgramParameter(a,35382);++b)a.ve=Math.max(a.ve,T.getActiveUniformBlockName(a,b).length+1);G[c>>
2]=a.ve}else G[c>>2]=T.getProgramParameter(a,b);else Q(1281)},bc:function(a,b,c){c?G[c>>2]=T.getRenderbufferParameter(a,b):Q(1281)},za:function(a,b,c,e){a=T.getShaderInfoLog(fd[a]);null===a&&(a="(unknown error)");b=0<b&&e?ma(a,B,e,b):0;c&&(G[c>>2]=b)},Mb:function(a,b,c,e){a=T.getShaderPrecisionFormat(a,b);G[c>>2]=a.rangeMin;G[c+4>>2]=a.rangeMax;G[e>>2]=a.precision},ya:function(a,b,c){c?35716==b?(a=T.getShaderInfoLog(fd[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(fd[a]),
G[c>>2]=a?a.length+1:0):G[c>>2]=T.getShaderParameter(fd[a],b):Q(1281)},P:function(a){var b=kd[a];if(!b){switch(a){case 7939:b=T.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=ud(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||Q(1280);b=b&&ud(b);break;case 7938:b=T.getParameter(7938);b=2<=t.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=ud(b);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ud(b);break;default:Q(1280)}kd[a]=b}return b},lb:function(a,b){if(2>t.version)return Q(1282),0;var c=ld[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=T.getSupportedExtensions()||[],c=c.concat(c.map(function(e){return"GL_"+e})),c=c.map(function(e){return ud(e)}),c=ld[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},xa:function(a,b){b=Na(b);if(a=cd[a]){var c=a,e=c.oe,f=c.Qe,
k;if(!e)for(c.oe=e={},c.Pe={},k=0;k<T.getProgramParameter(c,35718);++k){var l=T.getActiveUniform(c,k);var m=l.name;l=l.size;var q=wd(m);q=0<q?m.slice(0,q):m;var x=c.He;c.He+=l;f[q]=[l,x];for(m=0;m<l;++m)e[x]=m,c.Pe[x++]=q}c=a.oe;e=0;f=b;k=wd(b);0<k&&(e=parseInt(b.slice(k+1))>>>0,f=b.slice(0,k));if((f=a.Qe[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||T.getUniformLocation(a,b)))return e}else Q(1281);return-1},Ob:function(a,b,c){for(var e=rd[b],f=0;f<b;f++)e[f]=G[c+4*f>>2];T.invalidateFramebuffer(a,e)},Nb:function(a,
b,c,e,f,k,l){for(var m=rd[b],q=0;q<b;q++)m[q]=G[c+4*q>>2];T.invalidateSubFramebuffer(a,m,e,f,k,l)},Wb:function(a){return T.isSync(jd[a])},wa:function(a){return(a=ha[a])?T.isTexture(a):0},va:function(a){T.lineWidth(a)},ua:function(a){a=cd[a];T.linkProgram(a);a.oe=0;a.Qe={}},rc:function(a,b,c,e,f,k){T.Ne.multiDrawArraysInstancedBaseInstanceWEBGL(a,G,b>>2,G,c>>2,G,e>>2,$a,f>>2,k)},qc:function(a,b,c,e,f,k,l,m){T.Ne.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,G,b>>2,c,G,e>>2,G,f>>2,G,k>>2,
$a,l>>2,m)},ta:function(a,b){3317==a&&(nd=b);T.pixelStorei(a,b)},sc:function(a){T.readBuffer(a)},sa:function(a,b,c,e,f,k,l){if(2<=t.version)if(T.Ce)T.readPixels(a,b,c,e,f,k,l);else{var m=xd(k);T.readPixels(a,b,c,e,f,k,m,l>>31-Math.clz32(m.BYTES_PER_ELEMENT))}else(l=yd(k,f,c,e,l))?T.readPixels(a,b,c,e,f,k,l):Q(1280)},ac:function(a,b,c,e){T.renderbufferStorage(a,b,c,e)},_b:function(a,b,c,e,f){T.renderbufferStorageMultisample(a,b,c,e,f)},Sb:function(a,b,c){T.samplerParameterf(hd[a],b,c)},Rb:function(a,
b,c){T.samplerParameteri(hd[a],b,c)},Qb:function(a,b,c){T.samplerParameteri(hd[a],b,G[c>>2])},ra:function(a,b,c,e){T.scissor(a,b,c,e)},qa:function(a,b,c,e){for(var f="",k=0;k<b;++k){var l=e?G[e+4*k>>2]:-1;f+=Na(G[c+4*k>>2],0>l?void 0:l)}T.shaderSource(fd[a],f)},pa:function(a,b,c){T.stencilFunc(a,b,c)},oa:function(a,b,c,e){T.stencilFuncSeparate(a,b,c,e)},na:function(a){T.stencilMask(a)},ma:function(a,b){T.stencilMaskSeparate(a,b)},la:function(a,b,c){T.stencilOp(a,b,c)},ka:function(a,b,c,e){T.stencilOpSeparate(a,
b,c,e)},ja:function(a,b,c,e,f,k,l,m,q){if(2<=t.version)if(T.fe)T.texImage2D(a,b,c,e,f,k,l,m,q);else if(q){var x=xd(m);T.texImage2D(a,b,c,e,f,k,l,m,x,q>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else T.texImage2D(a,b,c,e,f,k,l,m,null);else T.texImage2D(a,b,c,e,f,k,l,m,q?yd(m,l,e,f,q):null)},ia:function(a,b,c){T.texParameterf(a,b,c)},ha:function(a,b,c){T.texParameterf(a,b,J[c>>2])},ga:function(a,b,c){T.texParameteri(a,b,c)},dd:function(a,b,c){T.texParameteri(a,b,G[c>>2])},oc:function(a,b,c,e,f){T.texStorage2D(a,
b,c,e,f)},cd:function(a,b,c,e,f,k,l,m,q){if(2<=t.version)if(T.fe)T.texSubImage2D(a,b,c,e,f,k,l,m,q);else if(q){var x=xd(m);T.texSubImage2D(a,b,c,e,f,k,l,m,x,q>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else T.texSubImage2D(a,b,c,e,f,k,l,m,null);else x=null,q&&(x=yd(m,l,f,k,q)),T.texSubImage2D(a,b,c,e,f,k,l,m,x)},bd:function(a,b){T.uniform1f(U(a),b)},ad:function(a,b,c){if(2<=t.version)T.uniform1fv(U(a),J,c>>2,b);else{if(288>=b)for(var e=zd[b-1],f=0;f<b;++f)e[f]=J[c+4*f>>2];else e=J.subarray(c>>2,c+4*b>>
2);T.uniform1fv(U(a),e)}},$c:function(a,b){T.uniform1i(U(a),b)},_c:function(a,b,c){if(2<=t.version)T.uniform1iv(U(a),G,c>>2,b);else{if(288>=b)for(var e=Ad[b-1],f=0;f<b;++f)e[f]=G[c+4*f>>2];else e=G.subarray(c>>2,c+4*b>>2);T.uniform1iv(U(a),e)}},Zc:function(a,b,c){T.uniform2f(U(a),b,c)},Yc:function(a,b,c){if(2<=t.version)T.uniform2fv(U(a),J,c>>2,2*b);else{if(144>=b)for(var e=zd[2*b-1],f=0;f<2*b;f+=2)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2];else e=J.subarray(c>>2,c+8*b>>2);T.uniform2fv(U(a),e)}},Xc:function(a,
b,c){T.uniform2i(U(a),b,c)},Wc:function(a,b,c){if(2<=t.version)T.uniform2iv(U(a),G,c>>2,2*b);else{if(144>=b)for(var e=Ad[2*b-1],f=0;f<2*b;f+=2)e[f]=G[c+4*f>>2],e[f+1]=G[c+(4*f+4)>>2];else e=G.subarray(c>>2,c+8*b>>2);T.uniform2iv(U(a),e)}},Vc:function(a,b,c,e){T.uniform3f(U(a),b,c,e)},Uc:function(a,b,c){if(2<=t.version)T.uniform3fv(U(a),J,c>>2,3*b);else{if(96>=b)for(var e=zd[3*b-1],f=0;f<3*b;f+=3)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2],e[f+2]=J[c+(4*f+8)>>2];else e=J.subarray(c>>2,c+12*b>>2);T.uniform3fv(U(a),
e)}},Tc:function(a,b,c,e){T.uniform3i(U(a),b,c,e)},Sc:function(a,b,c){if(2<=t.version)T.uniform3iv(U(a),G,c>>2,3*b);else{if(96>=b)for(var e=Ad[3*b-1],f=0;f<3*b;f+=3)e[f]=G[c+4*f>>2],e[f+1]=G[c+(4*f+4)>>2],e[f+2]=G[c+(4*f+8)>>2];else e=G.subarray(c>>2,c+12*b>>2);T.uniform3iv(U(a),e)}},Rc:function(a,b,c,e,f){T.uniform4f(U(a),b,c,e,f)},Qc:function(a,b,c){if(2<=t.version)T.uniform4fv(U(a),J,c>>2,4*b);else{if(72>=b){var e=zd[4*b-1],f=J;c>>=2;for(var k=0;k<4*b;k+=4){var l=c+k;e[k]=f[l];e[k+1]=f[l+1];e[k+
2]=f[l+2];e[k+3]=f[l+3]}}else e=J.subarray(c>>2,c+16*b>>2);T.uniform4fv(U(a),e)}},Pc:function(a,b,c,e,f){T.uniform4i(U(a),b,c,e,f)},Oc:function(a,b,c){if(2<=t.version)T.uniform4iv(U(a),G,c>>2,4*b);else{if(72>=b)for(var e=Ad[4*b-1],f=0;f<4*b;f+=4)e[f]=G[c+4*f>>2],e[f+1]=G[c+(4*f+4)>>2],e[f+2]=G[c+(4*f+8)>>2],e[f+3]=G[c+(4*f+12)>>2];else e=G.subarray(c>>2,c+16*b>>2);T.uniform4iv(U(a),e)}},Nc:function(a,b,c,e){if(2<=t.version)T.uniformMatrix2fv(U(a),!!c,J,e>>2,4*b);else{if(72>=b)for(var f=zd[4*b-1],
k=0;k<4*b;k+=4)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2];else f=J.subarray(e>>2,e+16*b>>2);T.uniformMatrix2fv(U(a),!!c,f)}},Mc:function(a,b,c,e){if(2<=t.version)T.uniformMatrix3fv(U(a),!!c,J,e>>2,9*b);else{if(32>=b)for(var f=zd[9*b-1],k=0;k<9*b;k+=9)f[k]=J[e+4*k>>2],f[k+1]=J[e+(4*k+4)>>2],f[k+2]=J[e+(4*k+8)>>2],f[k+3]=J[e+(4*k+12)>>2],f[k+4]=J[e+(4*k+16)>>2],f[k+5]=J[e+(4*k+20)>>2],f[k+6]=J[e+(4*k+24)>>2],f[k+7]=J[e+(4*k+28)>>2],f[k+8]=J[e+(4*k+32)>>2];
else f=J.subarray(e>>2,e+36*b>>2);T.uniformMatrix3fv(U(a),!!c,f)}},Lc:function(a,b,c,e){if(2<=t.version)T.uniformMatrix4fv(U(a),!!c,J,e>>2,16*b);else{if(18>=b){var f=zd[16*b-1],k=J;e>>=2;for(var l=0;l<16*b;l+=16){var m=e+l;f[l]=k[m];f[l+1]=k[m+1];f[l+2]=k[m+2];f[l+3]=k[m+3];f[l+4]=k[m+4];f[l+5]=k[m+5];f[l+6]=k[m+6];f[l+7]=k[m+7];f[l+8]=k[m+8];f[l+9]=k[m+9];f[l+10]=k[m+10];f[l+11]=k[m+11];f[l+12]=k[m+12];f[l+13]=k[m+13];f[l+14]=k[m+14];f[l+15]=k[m+15]}}else f=J.subarray(e>>2,e+64*b>>2);T.uniformMatrix4fv(U(a),
!!c,f)}},Kc:function(a){a=cd[a];T.useProgram(a);T.Ze=a},Jc:function(a,b){T.vertexAttrib1f(a,b)},Ic:function(a,b){T.vertexAttrib2f(a,J[b>>2],J[b+4>>2])},Hc:function(a,b){T.vertexAttrib3f(a,J[b>>2],J[b+4>>2],J[b+8>>2])},Gc:function(a,b){T.vertexAttrib4f(a,J[b>>2],J[b+4>>2],J[b+8>>2],J[b+12>>2])},nc:function(a,b){T.vertexAttribDivisor(a,b)},mc:function(a,b,c,e,f){T.vertexAttribIPointer(a,b,c,e,f)},Fc:function(a,b,c,e,f,k){T.vertexAttribPointer(a,b,c,!!e,f,k)},Ec:function(a,b,c,e){T.viewport(a,b,c,e)},
nb:function(a,b,c,e){T.waitSync(jd[a],b,(c>>>0)+4294967296*e)},S:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{Ia.grow(Math.min(2147483648,e)-Ya.byteLength+65535>>>16);bb();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},Pb:function(){return t?t.lf:0},Ab:function(a,b){var c=0;Cd().forEach(function(e,f){var k=b+c;f=G[a+4*f>>2]=k;for(k=0;k<e.length;++k)Za[f++>>
0]=e.charCodeAt(k);Za[f>>0]=0;c+=e.length+1});return 0},Bb:function(a,b){var c=Cd();G[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});G[b>>2]=e;return 0},T:function(){return 0},qb:function(a,b,c,e,f,k){a=vb.gf(a);b=vb.af(a,b,c,e);G[k>>2]=b;return 0},Hb:function(a,b,c,e){a=vb.gf(a);b=vb.af(a,b,c);G[e>>2]=b;return 0},rb:function(){},Gb:function(a,b,c,e){for(var f=0,k=0;k<c;k++){var l=G[b>>2],m=G[b+4>>2];b+=8;for(var q=0;q<m;q++){var x=B[l+q],y=ub[a];0===x||10===x?((1===a?Da:Ea)(La(y,0)),
y.length=0):y.push(x)}f+=m}G[e>>2]=f;return 0},a:function(){return Fa},o:Sd,t:Td,x:Ud,G:Vd,tb:Wd,_:Xd,pb:Yd,I:Zd,n:$d,e:ae,j:be,m:ce,ub:de,Y:ee,Z:fe,R:ge,b:function(a){Fa=a},wb:function(a,b,c,e){return Jd(a,b,c,e)}};
(function(){function a(f){r.asm=f.exports;Ia=r.asm.ed;bb();cb=r.asm.ld;eb.unshift(r.asm.fd);ib--;r.monitorRunDependencies&&r.monitorRunDependencies(ib);0==ib&&(null!==jb&&(clearInterval(jb),jb=null),kb&&(f=kb,kb=null,f()))}function b(f){a(f.instance)}function c(f){return pb().then(function(k){return WebAssembly.instantiate(k,e)}).then(function(k){return k}).then(f,function(k){Ea("failed to asynchronously prepare wasm: "+k);Ha(k)})}var e={a:he};ib++;r.monitorRunDependencies&&r.monitorRunDependencies(ib);
if(r.instantiateWasm)try{return r.instantiateWasm(e,a)}catch(f){return Ea("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Ga||"function"!==typeof WebAssembly.instantiateStreaming||lb()||mb.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(mb,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(k){Ea("wasm streaming compile failed: "+k);Ea("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ea);
return{}})();r.___wasm_call_ctors=function(){return(r.___wasm_call_ctors=r.asm.fd).apply(null,arguments)};var Rd=r.___errno_location=function(){return(Rd=r.___errno_location=r.asm.gd).apply(null,arguments)},Cc=r._free=function(){return(Cc=r._free=r.asm.hd).apply(null,arguments)},vd=r._malloc=function(){return(vd=r._malloc=r.asm.id).apply(null,arguments)},Bc=r.___getTypeName=function(){return(Bc=r.___getTypeName=r.asm.jd).apply(null,arguments)};
r.___embind_register_native_and_builtin_types=function(){return(r.___embind_register_native_and_builtin_types=r.asm.kd).apply(null,arguments)};var Qd=r._memalign=function(){return(Qd=r._memalign=r.asm.md).apply(null,arguments)},X=r._setThrew=function(){return(X=r._setThrew=r.asm.nd).apply(null,arguments)},Y=r.stackSave=function(){return(Y=r.stackSave=r.asm.od).apply(null,arguments)},Z=r.stackRestore=function(){return(Z=r.stackRestore=r.asm.pd).apply(null,arguments)};
r.dynCall_iiiij=function(){return(r.dynCall_iiiij=r.asm.qd).apply(null,arguments)};r.dynCall_viiij=function(){return(r.dynCall_viiij=r.asm.rd).apply(null,arguments)};r.dynCall_iiij=function(){return(r.dynCall_iiij=r.asm.sd).apply(null,arguments)};r.dynCall_viij=function(){return(r.dynCall_viij=r.asm.td).apply(null,arguments)};r.dynCall_iiiji=function(){return(r.dynCall_iiiji=r.asm.ud).apply(null,arguments)};var ie=r.dynCall_iiijiii=function(){return(ie=r.dynCall_iiijiii=r.asm.vd).apply(null,arguments)};
r.dynCall_jiiiiji=function(){return(r.dynCall_jiiiiji=r.asm.wd).apply(null,arguments)};r.dynCall_jiiiiii=function(){return(r.dynCall_jiiiiii=r.asm.xd).apply(null,arguments)};r.dynCall_jiji=function(){return(r.dynCall_jiji=r.asm.yd).apply(null,arguments)};r.dynCall_viji=function(){return(r.dynCall_viji=r.asm.zd).apply(null,arguments)};r.dynCall_viiiiij=function(){return(r.dynCall_viiiiij=r.asm.Ad).apply(null,arguments)};r.dynCall_jii=function(){return(r.dynCall_jii=r.asm.Bd).apply(null,arguments)};
r.dynCall_vij=function(){return(r.dynCall_vij=r.asm.Cd).apply(null,arguments)};r.dynCall_ji=function(){return(r.dynCall_ji=r.asm.Dd).apply(null,arguments)};r.dynCall_iij=function(){return(r.dynCall_iij=r.asm.Ed).apply(null,arguments)};r.dynCall_iijj=function(){return(r.dynCall_iijj=r.asm.Fd).apply(null,arguments)};r.dynCall_iiji=function(){return(r.dynCall_iiji=r.asm.Gd).apply(null,arguments)};r.dynCall_iijjiii=function(){return(r.dynCall_iijjiii=r.asm.Hd).apply(null,arguments)};
r.dynCall_vijjjii=function(){return(r.dynCall_vijjjii=r.asm.Id).apply(null,arguments)};r.dynCall_viijii=function(){return(r.dynCall_viijii=r.asm.Jd).apply(null,arguments)};r.dynCall_iiiiij=function(){return(r.dynCall_iiiiij=r.asm.Kd).apply(null,arguments)};r.dynCall_iiiiijj=function(){return(r.dynCall_iiiiijj=r.asm.Ld).apply(null,arguments)};r.dynCall_iiiiiijj=function(){return(r.dynCall_iiiiiijj=r.asm.Md).apply(null,arguments)};
function ae(a,b,c){var e=Y();try{N(a)(b,c)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}function Td(a,b,c){var e=Y();try{return N(a)(b,c)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}function Sd(a,b){var c=Y();try{return N(a)(b)}catch(e){Z(c);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function $d(a,b){var c=Y();try{N(a)(b)}catch(e){Z(c);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}
function Ud(a,b,c,e){var f=Y();try{return N(a)(b,c,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}function be(a,b,c,e){var f=Y();try{N(a)(b,c,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}function ce(a,b,c,e,f){var k=Y();try{N(a)(b,c,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function Zd(a){var b=Y();try{N(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}
function Xd(a,b,c,e,f,k,l){var m=Y();try{return N(a)(b,c,e,f,k,l)}catch(q){Z(m);if(q!==q+0&&"longjmp"!==q)throw q;X(1,0)}}function fe(a,b,c,e,f,k,l,m){var q=Y();try{N(a)(b,c,e,f,k,l,m)}catch(x){Z(q);if(x!==x+0&&"longjmp"!==x)throw x;X(1,0)}}function ge(a,b,c,e,f,k,l,m,q){var x=Y();try{N(a)(b,c,e,f,k,l,m,q)}catch(y){Z(x);if(y!==y+0&&"longjmp"!==y)throw y;X(1,0)}}function Vd(a,b,c,e,f){var k=Y();try{return N(a)(b,c,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}
function de(a,b,c,e,f,k){var l=Y();try{N(a)(b,c,e,f,k)}catch(m){Z(l);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function Wd(a,b,c,e,f,k){var l=Y();try{return N(a)(b,c,e,f,k)}catch(m){Z(l);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function ee(a,b,c,e,f,k,l){var m=Y();try{N(a)(b,c,e,f,k,l)}catch(q){Z(m);if(q!==q+0&&"longjmp"!==q)throw q;X(1,0)}}function Yd(a,b,c,e,f,k,l,m){var q=Y();try{return ie(a,b,c,e,f,k,l,m)}catch(x){Z(q);if(x!==x+0&&"longjmp"!==x)throw x;X(1,0)}}var je;
kb=function ke(){je||le();je||(kb=ke)};
function le(){function a(){if(!je&&(je=!0,r.calledRun=!0,!Ja)){qb(eb);ba(r);if(r.onRuntimeInitialized)r.onRuntimeInitialized();if(r.postRun)for("function"==typeof r.postRun&&(r.postRun=[r.postRun]);r.postRun.length;){var b=r.postRun.shift();fb.unshift(b)}qb(fb)}}if(!(0<ib)){if(r.preRun)for("function"==typeof r.preRun&&(r.preRun=[r.preRun]);r.preRun.length;)hb();qb(db);0<ib||(r.setStatus?(r.setStatus("Running..."),setTimeout(function(){setTimeout(function(){r.setStatus("")},1);a()},1)):a())}}
r.run=le;if(r.preInit)for("function"==typeof r.preInit&&(r.preInit=[r.preInit]);0<r.preInit.length;)r.preInit.pop()();le();


  return CanvasKitInit.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = CanvasKitInit;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return CanvasKitInit; });
else if (typeof exports === 'object')
  exports["CanvasKitInit"] = CanvasKitInit;
