name: smart_arrays_contour_finder_example
version: "3.0.0"
description: For Example This package contours the 3-dimensional surface represented by the values f(x,y) of a matrix. The detected contour lines are passed on to a user-provided renderer.
homepage: https://github.com/timmaffett/smart_packages
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  smart_arrays_base: #^3.0.0
    path: ../../smart_arrays_base  
  smart_arrays_dbstore: #^3.0.0
    path: ../../smart_arrays_dbstore  
  smart_arrays_plot_polyline: #^3.0.0
    path: ../../smart_arrays_plot_polyline

dev-dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^2.0.1
